### ISSUE TITLE
KeyError: u'function' when running powerline

### ISSUE THREAD

**Issue by keramidasceid** [powerline/powerline#1101]
When i open the terminal i see the folowing errors:

2014-09-29 12:04:51,090:ERROR:shell:segment_generator:Failed to generate segment from {u'name': u'hostname'}: u'function'
Traceback (most recent call last):
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 298, in get
    contents, _contents_func, module, function_name, name = get_segment_info(data, segment)
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 62, in get_function
    function_name = segment['function']
KeyError: u'function'
2014-09-29 12:04:51,090:ERROR:shell:segment_generator:Failed to generate segment from {u'name': u'user'}: u'function'
Traceback (most recent call last):
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 298, in get
    contents, _contents_func, module, function_name, name = get_segment_info(data, segment)
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 62, in get_function
    function_name = segment['function']
KeyError: u'function'
2014-09-29 12:04:51,091:ERROR:shell:segment_generator:Failed to generate segment from {u'name': u'virtualenv'}: u'function'
Traceback (most recent call last):
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 298, in get
    contents, _contents_func, module, function_name, name = get_segment_info(data, segment)
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 62, in get_function
    function_name = segment['function']
KeyError: u'function'
2014-09-29 12:04:51,091:ERROR:shell:segment_generator:Failed to generate segment from {u'name': u'branch'}: u'function'
Traceback (most recent call last):
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 298, in get
    contents, _contents_func, module, function_name, name = get_segment_info(data, segment)
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 62, in get_function
    function_name = segment['function']
KeyError: u'function'
2014-09-29 12:04:51,091:ERROR:shell:segment_generator:Failed to generate segment from {u'args': {u'dir_limit_depth': 3}, u'name': u'cwd'}: u'function'
Traceback (most recent call last):
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 298, in get
    contents, _contents_func, module, function_name, name = get_segment_info(data, segment)
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 62, in get_function
    function_name = segment['function']
KeyError: u'function'
2014-09-29 12:04:51,091:ERROR:shell:segment_generator:Failed to generate segment from {u'name': u'last_status', u'module': u'powerline.segments.shell'}: u'function'
Traceback (most recent call last):
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 298, in get
    contents, _contents_func, module, function_name, name = get_segment_info(data, segment)
  File "/home/keramidas/.local/lib/python2.7/site-packages/powerline/segment.py", line 62, in get_function
    function_name = segment['function']
KeyError: u'function'

**Comment by drselump14** [comment]
I had then same error , then I found that the problem was lying on my old ~/.conf/powerline ... remove it , and everything works fine

**Comment by preoctopus** [comment]
This comment just saved my sanity. @drselump14
