### ISSUE TITLE
Python errors with VCS segment in bash

### ISSUE THREAD

**Issue by mhartington** [powerline/powerline#1108]
This could very well be an issue on my end, but I couldn't find any relative information about it.

I included the VCS segment for my shell, bash, and it throws an error when you try to include the status color argument.

``` json
            {
                "function": "powerline.segments.common.vcs.branch",
                "priority": 10,
                "args": {
                    "status_colors": true
                }
            }
```

With that included, when I navigate to a git repo, I get an error message that is repeated for about 2000 lines before it "works"

``` bash
2014-10-06 10:47 Python[6256] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```

**Comment by thierrybo** [comment]
Hi,

in which version is this fixed? I currently run 2.5 from Debian Stretch repositories, and I have the issue on some git repositories, not all. For example git clone git://git.suckless.org/st 
```
cd ~/Sys/GIT.local.repositories/st
2018-05-01 16:41:20,241:ERROR:shell:branch:Exception while computing segment: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/powerline/segment.py", line 173, in process_segment
    contents = segment['contents_func'](pl, segment_info)
  File "/usr/lib/python2.7/dist-packages/powerline/segment.py", line 412, in <lambda>
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, segment_info=segment_info, **args)
  File "/usr/lib/python2.7/dist-packages/powerline/segments/common/vcs.py", line 33, in __call__
    if status in ignore_statuses:
TypeError: coercing to Unicode: need string or buffer, NoneType found

```
![powerline_stats_colors_true 01-05-2018 16-33](https://user-images.githubusercontent.com/3847603/39477073-6a37e470-4d5e-11e8-8ac5-3aec0aebb3f4.gif)
