### ISSUE TITLE
renaming attr to attrs missed at least one

### ISSUE THREAD

**Issue by mike-hart** [powerline/powerline#1248]
Traceback (most recent call last):
  File "powerline/scripts/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "powerline/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "powerline/powerline/bindings/config.py", line 139, in init_environment
    attrs = attr_to_tmux_attr(get_highlighting(group)[attr])
NameError: global name 'attr_to_tmux_attr' is not defined

attr_to_tmux_attr should probably be replaced with attrs_to_tmux_attrs if following the same pattern of renaming attr to attrs (or the defined function itself should be renamed to retain its singular?)

**Comment by mike-hart** [comment]
Error can be generated by running:

powerline/scripts/powerline-config tmux setenv
