### ISSUE TITLE
Error on vim

### ISSUE THREAD

**Issue by AlexTalker** [powerline/powerline#1261]
I am not sure this report doesn't repeat something, but:
```
2015-01-09 01:54:39,165:ERROR:vim:matcher_generator:Failed to import attr ctrlp from module powerline.matchers.vim.plugin.ctrlp: No module named 'powerline.matchers.vim.plugin.ctrlp'
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/powerline/__init__.py", line 317, in get_module_attr
    return getattr(__import__(module, fromlist=(attr,)), attr)
ImportError: No module named 'powerline.matchers.vim.plugin.ctrlp'

```
Vim version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  8 2015 03:14:08)
Included patches: 1-567
Compiled by ArchLinux
Big version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    -netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lncurses -lelf    -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc    -lruby -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib   
```
Powerline version: commit: `886c38c37bf8c797f65d7bb2a4e5bf4f7a82d571`

What must I do?

**Comment by ZyX-I** [comment]
I guess you have local configuration from some older commit. You must remove CtrlP matcher from your configuration because CtrlP support was removed. Run `powerline-lint`, it should tell you where exactly this matcher is set.

In all cases when you see some error with powerline run powerline-lint. If it is any kind of configuration error powerline-lint should catch it.

**Comment by AlexTalker** [comment]
I did remove:
`"powerline.matchers.vim.plugin.ctrlp.ctrlp": "plugin_ctrlp",`
Now everything fine.

**Comment by ZyX-I** [comment]
@AlexTalker. I have no idea what this may be, especially without stack trace and without details on circumstances under which you get it (in existing Vim just after updating config (== due to automatic config reloading feature), in new Vim after startup, …). Also you must first check `powerline-lint`.

If stack trace is there it most likely is in `:messages`.

**Comment by AlexTalker** [comment]
@ZyX-I, `powerline-lint`: https://gist.github.com/467ff77d9f2007c202b2
`:messages`:
```
2015-01-09 15:59:12,776:ERROR:vim:Failed to set highlight group: sequence item 0: expected str instance, NoneType found               
Traceback (most recent call last):                                                                                                    
  File "/usr/lib/python3.4/site-packages/powerline/segment.py", line 147, in set_segment_highlighting                                 
    segment.get('gradient_level')                                                                                                     
  File "/usr/lib/python3.4/site-packages/powerline/colorscheme.py", line 105, in get_highlighting                                     
    raise KeyError('Highlighting groups not found in colorscheme: ' + ', '.join(groups))                                              
TypeError: sequence item 0: expected str instance, NoneType found  
```

**Comment by ZyX-I** [comment]
@AlexTalker It is pretty much telling you all of the errors. You have outdated configuration: `attr` key in colorschemes was renamed into `attrs` and `powerline-lint` is showing you where. You also have `now_playing` segment which was also removed (check [the documentation](https://powerline.readthedocs.org/en/latest/configuration/segments/common.html#module-powerline.segments.common.players), it shows how player segments should be added now). `highlight_group` key was renamed into `highlight_groups`. If you do not want to see all these errors use PyPI `powerline-status`, *not* github repository because I am preparing 2.0 release with a bunch of incompatible changes (notes on migration will be listed in release documentation).
