### ISSUE TITLE
KeyError: <type 'list'>

### ISSUE THREAD

**Issue by winds18** [powerline/powerline#1268]
``` python
ERROR:vim:visual_range:Exception while computing segment: <type 'list'>
Traceback (most recent call last):
  File "/usr/local/powerline/powerline/segment.py", line 169, in process_segment
    contents = segment['contents_func'](pl, segment_info)
  File "/usr/local/powerline/powerline/segment.py", line 405, in <lambda>
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, segment_info=segment_info, **args)
  File "/usr/local/powerline/powerline/segments/vim/__init__.py", line 77, in ret
    r = func(segment_info=segment_info, **kwargs)
  File "/usr/local/powerline/powerline/segments/vim/__init__.py", line 138, in visual_range
    svcol = vim_funcs['virtcol']([sline, scol, soff])
  File "/usr/local/powerline/powerline/bindings/vim/__init__.py", line 148, in __call__
    ))) + b')')
  File "/usr/local/powerline/powerline/bindings/vim/__init__.py", line 147, in <genexpr>
    python_to_vim(o) for o in args
  File "/usr/local/powerline/powerline/bindings/vim/__init__.py", line 60, in python_to_vim
    return python_to_vim_types[type(o)](o)
KeyError: <type 'list'>
```

**Comment by ZyX-I** [comment]
Github supports markdown. Do use it for formatting logs as code so that they will not be modified.

What Vim version?

**Comment by winds18** [comment]
vim7.3 of osx 10.10

**Comment by ZyX-I** [comment]
7.3 without patches?

**Comment by winds18** [comment]
i don't know how to see whether patched?

**Comment by ZyX-I** [comment]
@winds18 :version should tell you about patches, as well as `vim --version`. If they do not then this version is unpatched. Though it does not matter: the error is recognized as old-Vims-specific and I will submit a PR soon.

And format stack trace as code block.

**Comment by ZyX-I** [comment]
This should fix it.

**Comment by winds18** [comment]
i try now, thank you very much!
