### ISSUE TITLE
threaded.py interval

### ISSUE THREAD

**Issue by ShiroiKuma** [powerline/powerline#1301]
Once I added the weather segment to my config, I saw it a few times on my command line and then it vanished. This only happens with the daemon mode, not the script mode.

Running with powerline-daemon --replace --foreground produced the following errors:

<pre><code>Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/powerline/lib/threaded.py", line 91, in run
    self.shutdown_event.wait(max(self.interval - (monotonic() - start_time), self.min_sleep_time))
TypeError: unsupported operand type(s) for -: 'unicode' and 'float'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/powerline/lib/threaded.py", line 91, in run
    self.shutdown_event.wait(max(self.interval - (monotonic() - start_time), self.min_sleep_time))
TypeError: unsupported operand type(s) for -: 'unicode' and 'float'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/powerline/lib/threaded.py", line 91, in run
    self.shutdown_event.wait(max(self.interval - (monotonic() - start_time), self.min_sleep_time))
TypeError: unsupported operand type(s) for -: 'unicode' and 'float'

2015-02-07 18:34:58,625:ERROR:shell:WeatherSegment:Exception while updating: unsupported operand type(s) for +: 'float' and 'unicode'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/powerline/lib/threaded.py", line 71, in set_update_value
    self.update_value = self.update(self.update_value)
  File "/usr/lib/python2.7/site-packages/powerline/lib/threaded.py", line 240, in update
    if last_query_time < monotonic() < last_query_time + self.interval:
TypeError: unsupported operand type(s) for +: 'float' and 'unicode'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/powerline/lib/threaded.py", line 91, in run
    self.shutdown_event.wait(max(self.interval - (monotonic() - start_time), self.min_sleep_time))
TypeError: unsupported operand type(s) for -: 'unicode' and 'float'</code></pre>

Having investigated this, I've altered my own threaded.py on line 115 to force the keyword's value to a float.
   self.interval = float(interval)

After doing this, I'm no longer getting this error.

**Comment by ZyX-I** [comment]
Check out `powerline-lint` output. The only reason for `interval` to have `unicode` type I know is specifying wrong value in the user configuration. You must not force keywords value to a float, you should fix the real issue.

Also do format tracebacks as code, e.g. by wrapping them in a <code>\`\`\`\n…\n\`\`\`</code> or in `<pre>…</pre>`.

**Comment by ShiroiKuma** [comment]
Had to put them in <pre><code>…</code></pre> but that looks better.

Thanks for the powerline-lint tip, I had it set as "300" in the json instead of just 300. Now to fix a million other errors it's reporting.

**Comment by ZyX-I** [comment]
> Thanks for the powerline-lint tip, I had it set as "300" in the json instead of just 300. Now to fix a million other errors it's reporting.

It usually reports loads of errors if you have outdated configuration (i.e. I recently massively renamed some keys in configuration, check out changelog on github releases page for details).
