### ISSUE TITLE
Problem with creating custom color scheme for shell

### ISSUE THREAD

**Issue by sryze** [powerline/powerline#1304]
I just wanted to change one color in the default color scheme for shell, so I copied default.json from `powerline/config_files/colorschemes/shell/` to `~/.config/powerline/colorschemes/shell`, renamed it to `custom.json` and edited my `config.json` accordingly.

But it's not working for some reason and when I kill the `powerline-daemon` it spits out tons of errors:

```
Kill command sent to daemon, if it does not die in a couple of seconds use kill to kill it
2015-02-08 02:31:02,295:ERROR:shell:user:Failed to set highlight group: u'Highlighting groups not found in colorscheme: user'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/powerline/segment.py", line 147, in set_segment_highlighting
    segment.get('gradient_level')
  File "/usr/local/lib/python2.7/dist-packages/powerline/colorscheme.py", line 105, in get_highlighting
    raise KeyError('Highlighting groups not found in colorscheme: ' + ', '.join(groups))
KeyError: u'Highlighting groups not found in colorscheme: user'
2015-02-08 02:31:02,296:ERROR:shell:cwd:Failed to set highlight group: u'Highlighting groups not found in colorscheme: cwd:current_folder, cwd'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/powerline/segment.py", line 147, in set_segment_highlighting
    segment.get('gradient_level')
  File "/usr/local/lib/python2.7/dist-packages/powerline/colorscheme.py", line 105, in get_highlighting
    raise KeyError('Highlighting groups not found in colorscheme: ' + ', '.join(groups))
KeyError: u'Highlighting groups not found in colorscheme: cwd:current_folder, cwd'
2015-02-08 02:31:02,296:ERROR:shell:cwd:Failed to set highlight group: u'Highlighting groups not found in colorscheme: cwd'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/powerline/segment.py", line 147, in set_segment_highlighting
    segment.get('gradient_level')
  File "/usr/local/lib/python2.7/dist-packages/powerline/colorscheme.py", line 105, in get_highlighting
    raise KeyError('Highlighting groups not found in colorscheme: ' + ', '.join(groups))
KeyError: u'Highlighting groups not found in colorscheme: cwd'
```

Am I doing it wrong?

**Comment by ZyX-I** [comment]
Check out relevant section of the documentation. Colorscheme consists of *three* files and when you take one and *rename* it you automatically lose definitions from one of them.

**Comment by sryze** [comment]
Thanks! Though I don't see where the [docs](http://powerline.readthedocs.org/en/latest/configuration/reference.html#colorschemes) mention that you must have all three files exactly, I guess I must have overlooked that.

**Comment by ZyX-I** [comment]
@sryze You don’t have to have all three files exactly. But ***in the current configuration*** definitions of necessary highlight groups are scattered over *three* files. You have copied *one* from which I removed as much highlight groups as possible.

You could’ve placed everything in one file. But to do this you must understand what is going on, not copy files over the place.
