### ISSUE TITLE
tmux fails to raise statusline (green bar instead) using master branch of tmux [solved]

### ISSUE THREAD

**Issue by pcxmac** [powerline/powerline#1308]
hello, it's been a while since I have run tmux with powerline, before I have had really no issues Before I stopped using powerline I found that I had to manually set the background color to the tmux status line otherwise it was off color.

I would use this in the .tmux.conf

set -g status-style "bg=colour234"

now that I am using powerline again in tmux, the official way to install/config, I am having a problem getting tmux to execute powerline-config tmux setup. The PATH and POWERLINE_CONFIG_COMMAND are all set properly, and the command "powerline-config tmux setup" works AFTER i am in a tmux session (just not while starting tmux).

here is the redirected stderr/stdout for the command I ran (run-shell) from the tmux config while trying to execute powerline-config tmux setup.

```
can't establish current session
Traceback (most recent call last):
  File "/root/.local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/root/.local/lib/python3.4/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/root/.local/lib/python3.4/site-packages/powerline/bindings/config.py", line 168, in tmux_setup
    init_tmux_environment(pl, args)
  File "/root/.local/lib/python3.4/site-packages/powerline/bindings/config.py", line 116, in init_tmux_environment
    set_tmux_environment(varname, powerline.renderer.hlstyle(**highlight)[2:-1])
  File "/root/.local/lib/python3.4/site-packages/powerline/bindings/tmux/__init__.py", line 53, in set_tmux_environment
    run_tmux_command('set-environment', '-r', varname)
  File "/root/.local/lib/python3.4/site-packages/powerline/bindings/tmux/__init__.py", line 32, in run_tmux_command
    _run_tmux(subprocess.check_call, args)
  File "/root/.local/lib/python3.4/site-packages/powerline/bindings/tmux/__init__.py", line 27, in _run_tmux
    return runner([get_tmux_executable_name()] + list(args))
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tmux', 'set-environment', '-r', '_POWERLINE_BACKGROUND_COLOR']' returned non-zero exit status 1
```

it seems as though the "background color" might be causing problems.

tput colors reports "256", echo $TERM reports "screen-256color", I use rxvt-unicode compiled with --enable-unicode3, and have no problems with vim or zsh. Again, I can invoke powerline-config tmux setup after starting tmux, and I see everything I am supposed to, it just doesn't seem to work while binding/or running the command explicitly inside the .tmux.conf. 

source "/root/.local/lib/python3.4/site-packages/powerline/bindings/tmux/powerline.conf"

#set -g status-style "bg=colour234"

run-shell "powerline-config tmux setup &> /root/error.info"

**Comment by ZyX-I** [comment]
If you want to paste traceback or log here, ***do*** quote it as code.

Error when running `tmux set-environment` has *absolutely* nothing to do with colors. It is just failing to set some variable to some value and it is absolutely irrelevant that variable is named after its purpose (to hold background color value).

What is the tmux version?

**Comment by pcxmac** [comment]
awww, yes, of course I was using the master (tmux-code/github), 1.8 & 1.9 & 1.9a seem to work well. Thanks for your time :)

**Comment by netsamir** [comment]
Hi,

I have this issue and I can't solve it:
```
powerline-config tmux setup
no server running on /private/var/folders/_1/29gzrs8s7r51qb0fvgn2vwgh0000gn/T/tmux-501/default
Traceback (most recent call last):
  File "/Users/netsamir/local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/Users/netsamir/local/lib/python2.7/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/Users/netsamir/local/lib/python2.7/site-packages/powerline/bindings/config.py", line 168, in tmux_setup
    init_tmux_environment(pl, args)
  File "/Users/netsamir/local/lib/python2.7/site-packages/powerline/bindings/config.py", line 116, in init_tmux_environment
    set_tmux_environment(varname, powerline.renderer.hlstyle(**highlight)[2:-1])
  File "/Users/netsamir/local/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 51, in set_tmux_environment
    run_tmux_command('set-environment', '-g', varname, value)
  File "/Users/netsamir/local/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 32, in run_tmux_command
    _run_tmux(subprocess.check_call, args)
  File "/Users/netsamir/local/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 27, in _run_tmux
    return runner([get_tmux_executable_name()] + list(args))
  File "/Users/netsamir/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'tmux', u'set-environment', u'-g', u'_POWERLINE_BACKGROUND_COLOR', u'fg=colour117,bg=colour233,nobold,noitalics,nounderscore']' returned non-zero exit status 1
```

I run tmux version 2:
```
tmux 2.0
```
Then if I do that 
```
tmux set-environment _POWERLINE_BACKGROUND_COLOR color233

 >  powerline-config tmux setup
no current client
Traceback (most recent call last):
  File "/Users/netsamir/local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/Users/netsamir/local/lib/python2.7/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/Users/netsamir/local/lib/python2.7/site-packages/powerline/bindings/config.py", line 169, in tmux_setup
    source_tmux_files(pl, args)
  File "/Users/netsamir/local/lib/python2.7/site-packages/powerline/bindings/config.py", line 78, in source_tmux_files
    run_tmux_command('refresh-client')
  File "/Users/netsamir/local/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 32, in run_tmux_command
    _run_tmux(subprocess.check_call, args)
  File "/Users/netsamir/local/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 27, in _run_tmux
    return runner([get_tmux_executable_name()] + list(args))
  File "/Users/netsamir/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'tmux', u'refresh-client']' returned non-zero exit status 1
```

Please thank you to help me, I am struggling since 3 days.  It was working before even with another version of tmux.  There is something wrong but can't find where.

**Comment by ZyX-I** [comment]
Given

> no server running on /private/var/folders/_1/29gzrs8s7r51qb0fvgn2vwgh0000gn/T/tmux-501/default

it looks like if you are trying to run `powerline-config` not inside a tmux session or you have invalid `$TMUX` variable value.

The second case (when `tmux refresh-client` makes you kill tmux server for unknown reason) looks like a bug that should be redirected to tmux developers.

Also I do not see version `2.0` in https://sourceforge.net/p/tmux/tmux-code/ref/master/tags/. Development versions are not supported because it is fine for them to contain bugs which will disappear before the release. Or have a set of incompatible changes which will change before the release (I know that new version will not be fully compatible, though what I know does not touch powerline).

**Comment by netsamir** [comment]
Hi,

I have the same problem with version 1.9.  After having read the information provided here, I have used the master tmux version of github, this one: https://github.com/ThomasAdam/tmux.

I am running:
````
powerline-config tmux setup
``` 
from the content of the above file from ~/.tmux.conf: 
```
"$HOME/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"
```
to find this line:
```
if-shell 'env "$POWERLINE_CONFIG_COMMAND" tmux setup' '' 'run-shell "powerline-config tmux setup"'
```
outside tmux because it crashes.

I will downgrad tmux and revert back.  What is strange to me is that problem happened suddenly on both version.

**Comment by netsamir** [comment]
Hi, 

I have just removed my version 2.0, re-install version 1.9a and it works again.  It is very strange, it seems that some variable should be set somewhere. 

Thank you again for your help.

**Comment by netsamir** [comment]
We never know, it might help someone.  Installation of tmux locally, with ncurses and libevent.

```
# download source files for tmux, libevent, and ncurses                                                                                                                                                    
wget -O http://sourceforge.net/projects/tmux/files/tmux/tmux-1.9/tmux-1.9a.tar.gz/download
wget https://github.com/downloads/libevent/libevent/libevent-2.0.19-stable.tar.gz
wget ftp://ftp.gnu.org/gnu/ncurses/ncurses-5.9.tar.gz

# libevent

tar xvzf libevent-2.0.19-stable.tar.gz
cd libevent-2.0.19-stable
./configure --prefix=$HOME/local
make
make install
cd ..


# ncurses   - Note the --without-cxx-binding#


tar xvzf ncurses-5.9.tar.gz
cd ncurses-5.9
./configure --prefix=$HOME/local --without-cxx-binding
make
make install
cd ..

# Tmux
tar xvzf tmux-1.9a.tar.gz
cd tmux-1.9a
./configure CFLAGS="-I$HOME/local/include -I$HOME/local/include/ncurses" LDFLAGS="-L$HOME/local/lib -L$HOME/local/include/ncurses -L$HOME/local/include" --prefix=$HOME/local
CPPFLAGS="-I$HOME/local/include -I$HOME/local/include/ncurses" LDFLAGS="-static -L$HOME/local/include -L$HOME/local/include/ncurses -L$HOME/local/lib" make
make install
```
