### ISSUE TITLE
Qtile plugin crashes

### ISSUE THREAD

**Issue by jeLee6gi** [powerline/powerline#1313]
Adding the the code supplied in the documentation crashes my qtile installation:

```
$ python .config/qtile/config.py
Traceback (most recent call last):
  File ".config/qtile/config.py", line 174, in <module>
    Powerline(timeout=2),
  File "/usr/lib/python2.7/site-packages/powerline/bindings/qtile/widget.py", line 13, in __init__
    self.timeout_add(timeout, self.update)
  File "/usr/lib/python2.7/site-packages/libqtile/widget/base.py", line 169, in timeout_add
    return self.qtile.call_later(seconds, self._wrapper, method, *method_args)
  File "/usr/lib/python2.7/site-packages/libqtile/configurable.py", line 44, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: Powerline has no attribute: qtile
```

I'm running the latest "stable" version of qtile 0.9.1.

**Comment by ZyX-I** [comment]
I am unable to reproduce your issue with version 0.8, but found out that example config placed in documentation is wrong.

**Comment by ZyX-I** [comment]
And neither pip nor Gentoo portage knows about 0.9.1.

**Comment by ZyX-I** [comment]
Please check out whether #1314 works.

**Comment by jeLee6gi** [comment]
#1314 fixes the issue, thanks!
