### ISSUE TITLE
ERROR:shell:environment:Exception while computing segment: str expected, not bool

### ISSUE THREAD

**Issue by zchee** [powerline/powerline#1334]
I use tmux and zsh.
When I start the zsh using tmux, sometimes this error occurs.
What would be the best thing to do?

```
2015-03-15 17:02:13,355:ERROR:shell:environment:Exception while computing segment: str expected, not bool
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/powerline/segment.py", line 169, in process_segment
    contents = segment['contents_func'](pl, segment_info)
  File "/usr/local/lib/python3.5/site-packages/powerline/segment.py", line 405, in <lambda>
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, segment_info=segment_info, **args)
  File "/usr/local/lib/python3.5/site-packages/powerline/segments/common/env.py", line 18, in environment
    return segment_info['environ'].get(variable, None)
  File "/Users/zchee/.pyenv/versions/3.5-dev/lib/python3.5/_collections_abc.py", line 422, in get
    return self[key]
  File "/Users/zchee/.pyenv/versions/3.5-dev/lib/python3.5/os.py", line 634, in __getitem__
    value = self._data[self.encodekey(key)]
  File "/Users/zchee/.pyenv/versions/3.5-dev/lib/python3.5/os.py", line 710, in encode
    raise TypeError("str expected, not " type(value).__name__)
TypeError: str expected, not bool
```

Thanks.

**Comment by ZyX-I** [comment]
What is your configuration? This error looks like if you have

```JSON
{
    "function": "powerline.segments.common.env.evironment",
    "args": {
        "variable": true
    }
}
```

in your theme.
