### ISSUE TITLE
Is this repo workable as a submodule?

### ISSUE THREAD

**Issue by magicalbanana** [powerline/powerline#1340]
Because I have it a submodule on my dotfile repo and I get this error in my zsh when it starts:

```
Traceback (most recent call last):
  File "/Users/kgan/Git/dotfiles/powerline/client/powerline.py", line 57, in <module>
    os.execvp('powerline-render', args)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 346, in execvp
    _execvpe(file, args)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 382, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
```

**Comment by ZyX-I** [comment]
You can use it as a submodule if you link relevant files in some directory in `$PATH`. But this is not officially supported installation method (even though powerline contains some code that makes using it like this simpler) and will never be.

I would also highly suggest to install `socat` *or* compile powerline client (commands for compilation can be deduced by looking in `setup.py`) **and** run `{path-to}/powerline-daemon --quiet` in your shell rc file like suggested by documentation.
