### ISSUE TITLE
sourcing bash/powerline.sh fails

### ISSUE THREAD

**Issue by logol** [powerline/powerline#1357]
Hi, I'm getting errors on my 2nd PC, while powerline works on the first w/o problems. Both have the same architecture (64bit), OS (ArchLinux) and the same packages and configs.

---
When I source /usr/lib/python3.4/site-packages/powerline/bindings/bash/powerline.sh on my 2nd PC I get something like (powerline-daemon not running):
Traceback (most recent call last):
  File "/usr/bin/powerline-render", line 30, in <module>
    write_output(args, powerline, segment_info, get_unicode_writer())
  File "/usr/lib/python3.4/site-packages/powerline/commands/main.py", line 156, in write_output
    if args.side.startswith('above'):
AttributeError: 'list' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/bin/powerline-render", line 30, in <module>
    write_output(args, powerline, segment_info, get_unicode_writer())
  File "/usr/lib/python3.4/site-packages/powerline/commands/main.py", line 156, in write_output
    if args.side.startswith('above'):
AttributeError: 'list' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/bin/powerline-render", line 30, in <module>
    write_output(args, powerline, segment_info, get_unicode_writer())
  File "/usr/lib/python3.4/site-packages/powerline/commands/main.py", line 156, in write_output
    if args.side.startswith('above'):
AttributeError: 'list' object has no attribute 'startswith'

---
with powerline-daemon running I only get:
'list' object has no attribute 'startswith'

---
installed powerline via python3.4 pip (pip install powerline-status), fontconfig font installation and using it inside a bash shell in xfce4-terminal (http://powerline.readthedocs.org/en/latest/usage/shell-prompts.html#bash-prompt)

**Comment by logol** [comment]
ty, installed dev version via
`pip install git+git://github.com/powerline/powerline`
on 2nd PC and now it works :)
