### ISSUE TITLE
401:ERROR:vim:powerline:Failed to create renderer: [Errno 28] Auf dem Gerät ist kein Speicherplatz mehr verfügbarYou may need to increase the inotify limits on your system, via /proc/sys/inotify/max_user_*

### ISSUE THREAD

**Issue by neulaender** [powerline/powerline#1413]
Hello, I got some problems with my vim-powerline configuration. The notice to check my inotify limits at /proc/sys/inotify/max_user_* won't work, because the folder inotify is not existent.

```log
2015-07-18 14:20:56,401:ERROR:vim:powerline:Failed to create renderer: [Errno 28] Auf dem Gerät ist kein Speicherplatz mehr verfügbarYou may need to increase the inotify limits on your system, via /proc/sys/inotify/max_user_*
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/powerline/__init__.py", line 742, in update_renderer
    self.create_renderer(**cr_kwargs)
  File "/usr/lib/python3.4/site-packages/powerline/__init__.py", line 480, in create_renderer
    self.config_loader.set_watcher(self.common_config['watcher'])
  File "/usr/lib/python3.4/site-packages/powerline/lib/config.py", line 84, in set_watcher
    self.watcher.transfer_calls(watcher)
  File "/usr/lib/python3.4/site-packages/powerline/lib/config.py", line 49, in transfer_calls
    getattr(watcher, attr)(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/powerline/lib/watcher/inotify.py", line 100, in watch
    self.handle_error()
  File "/usr/lib/python3.4/site-packages/powerline/lib/inotify.py", line 138, in handle_error
    raise OSError(eno, self.os.strerror(eno) + str(extra))
OSError: [Errno 28] Auf dem Gerät ist kein Speicherplatz mehr verfügbarYou may need to increase the inotify limits on your system, via /proc/sys/inotify/max_user_*
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/usr/lib/python3.4/site-packages/powerline/__init__.py", line 796, in setup
    self.do_setup(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/powerline/vim.py", line 203, in do_setup
    self.update_renderer()
  File "/usr/lib/python3.4/site-packages/powerline/__init__.py", line 742, in update_renderer
    self.create_renderer(**cr_kwargs)
  File "/usr/lib/python3.4/site-packages/powerline/__init__.py", line 480, in create_renderer
    self.config_loader.set_watcher(self.common_config['watcher'])
  File "/usr/lib/python3.4/site-packages/powerline/lib/config.py", line 84, in set_watcher
    self.watcher.transfer_calls(watcher)
  File "/usr/lib/python3.4/site-packages/powerline/lib/config.py", line 49, in transfer_calls
    getattr(watcher, attr)(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/powerline/lib/watcher/inotify.py", line 100, in watch
    self.handle_error()
  File "/usr/lib/python3.4/site-packages/powerline/lib/inotify.py", line 138, in handle_error
    raise OSError(eno, self.os.strerror(eno) + str(extra))
OSError: [Errno 28] Auf dem Gerät ist kein Speicherplatz mehr verfügbarYou may need to increase the inotify limits on your system, via /proc/sys/inotify/max_user_*
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
```

**Comment by ZyX-I** [comment]
If you don’t have /proc/sys then you need to use sysctl. The relevant setting is fs.inotify.max_user_watches. /proc/sys is only a pseudo-filesystem that gives access to the same thing sysctl does.

Or you can disable inotify at all, check out config.json file description in configuration reference.

**Comment by ZyX-I** [comment]
It appears that error message is misleading: /proc/sys/inotify needs to be /proc/sys/fs/inotify.

**Comment by ZyX-I** [comment]
Error message was fixed. Note that to make changes permanent you need to use /etc/sysctl.conf (or any alternative from your distribution if any.)

**Comment by domgetter** [comment]
I had a very similar problem because I put a trailing comma in an array in `config.json`

To anyone else having issues, make sure your json files are valid json!
