### ISSUE TITLE
Powerline's bash prompt hangs upon 'cd' to certain directories

### ISSUE THREAD

**Issue by cviner** [powerline/powerline#1494]
The Powerline bash prompt hangs upon issuing a `cd` command to a number of directories. Neither sending `SIGINT` nor `SIGTSTP` are sufficient to recover control of affected prompts. Those directories can be listed fine with the Powerline prompt and `cd` works when not using the Powerline bash prompt.

The directories that this occurs in appear to all have (valid) symbolic links contained within them. However, I cannot reproduce this issue by creating another directory with symbolic links elsewhere, so this may simply be coincidental. All directories that were confirmed to be affected by this resided within a single user-created directory, but again this is likely to be coincidental and due to a lack of systematic directory traversal.

**Comment by ZyX-I** [comment]
Please show me a script which reproduces this issue. Without it report is useless. Also check that using `python -c 'import os; print(getattr(os, "getcwdu", os.getcwd)())'` does *not* hang. If it does the issue should be reported to Python developers.

Also are you using daemon or not? If yes, what is the output of `file $(which powerline)` and `head -n1 $(which powerline)` (second is needed only if first reports that `powerline` is not an ELF binary).

Also I would like to see hanging directory names, full variant.

**Comment by cviner** [comment]
The script is literally the change directory command alone, e.g. `cd ` *X*, where *X* is a directory that causes this issue.

I can confirm that the Python one-liner you provided does not hang without Powerline. Of course the test is only meaningful with the Powerline prompt, however I cannot test that directly, since I cannot enter that directory with the Powerline prompt. Even attempting to execute `.../powerline/bindings/bash/powerline.sh` from within a directory which I cannot `cd` into with the Powerline prompt active hangs.

Accordingly, I instead tested the following, for a particular directory `X`:

```python
python -c 'import os; os.chdir("X"); print(getattr(os, "getcwdu", os.getcwd)())'
```
The above Python one-liner completed successfully and output the path `X`.

I am indeed using the daemon:
```bash
$ file $(which powerline)
```
```text
/mnt/work1/users/home2/cviner/.local/bin/powerline: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, not stripped
```

Here is one full example of full directory paths that hang.

```text
~/cytomod/experiments/linked-2015-07-09-ZFP57_mESC_ChIP-Seq_new_data_processing-mm10-stringent_only/
```

I can confirm that the issue occurs after the completion of `cd` itself and (apparently) during the computation to or rendering of the Powerline prompt. That is, `cd "X"; pwd;` outputs the correct directory path (`"X"`), but then hangs prior to the rendering of the prompt.

I have now been able to reproduce this on another machine as well. The issue appears to also occur for longer directory paths (i.e. long directory paths appear sufficient, but not necessary, for this issue to manifest).

I have also recently found a number of counter-examples to my initial supposition that all directories that this occurred for contained symbolic links. For example, I was able to do `cd ~/cytomod/experiments/linked-2015-06-05-ModGenomeV7-MEME-ChIP_expanded_alphabet_runs/`, which contains symbolic links, without any issues.

**Comment by ZyX-I** [comment]
> The script is literally the change directory command alone, e.g. cd X, where X is a directory that causes this issue.

No. The script is “create directory that causes the issue, cd to it and run `powerline shell left`”. I cannot do anything without the first part.

**Comment by ZyX-I** [comment]
With daemon this would additionally be “launch the daemon (`powerline-daemon --socket /tmp/new-socket`)”, and “run `powerline shell left`” changes to “run `powerline --socket /tmp/new-socket shell left`”.

**Comment by cviner** [comment]
I can certainly understand your wanting a reproducible (and ideally minimal) example. Unfortunately, I have yet to be able to create one.

If what I have provided is not sufficient to investigate this at all, that's certainly understandable. In that case, this will have to wait until others encounter it or until I am able to investigate this is greater detail. Thanks for your input on this.

**Comment by ZyX-I** [comment]
@cviner By the way, does colon after “daemon” in “I am indeed using the daemon: {shell command} {shell command output}” mean that you said that you are using daemon based on that shell command output? If yes, this is not guaranteed to be true, `powerline` executable falls back to using `powerline-render`. Also I would like to ask you to check whether `powerline-render`, `client/powerline.py` and `client/powerline.sh` also have the same problem in case this is the problem with daemon (first variant is guaranteed not to use it) or C code (second two are clients written in POSIX shell language (third) and Python (second), shell script requires `socat` binary).

**Comment by ZyX-I** [comment]
With daemon it would also be good to check its log: run it with `--replace` (to replace existing one) and `--foreground` arguments in a different terminal window or use configuration files (~/.config/powerline/config.json, subdictionary “common”, key “log_file”) to direct log into some file.

**Comment by cviner** [comment]
Sorry, I should have been more clear in that regard. I meant that I am using the Powerline daemon (I know that independently of that test) and that I was accordingly providing the requested test output.

I'm not certain I am correctly testing the three things you requested, so please let me know if there is a specific way to test it that I missed.

With the daemon running already, I did the following, for `X`, a problematic directory:

```bash
cd X
. $HOME/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh
```
Confirmed that the above hangs (is this the `client/powerline.sh ` to which you refer?).

```bash
cd X
powerline-render shell left
```
Confirmed that the above worked fine.

How do I test `client/powerline.py` (i.e. where is that Python script located)?

I ran `powerline-daemon --replace --foreground` in one terminal window and from another on the same node ran `. $HOME/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh` from within `X`. The prompt hanged and the prompt with the daemon in the foreground had no output at all (perhaps I didn't correctly perform this test?).

**Comment by ZyX-I** [comment]
> Confirmed that the above hangs (is this the client/powerline.sh to which you refer?).

No, `client/powerline.sh` is `client/powerline.sh` from the repository. Not `powerline/bindings/bash/powerline.sh`. It is not installed by pip.

> How do I test client/powerline.py (i.e. where is that Python script located)?

In this repository. It is not installed by pip (actually it is, but only as a fall back when neither C compiler was found nor `socat` executable is available).

> The prompt hanged and the prompt with the daemon in the foreground had no output at all (perhaps I didn't correctly perform this test?).

Test is correct as far as I see.

**Comment by cviner** [comment]
Thanks for those details.

I have now tested both `client/powerline.sh` and `client/powerline.py` with arguments `shell left` from within a directory for which `. $HOME/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh` hangs.

`client/powerline.sh` results in `line 49: socat: command not found` (hopefully I don't need to install it to test this fully).

and

`client/powerline.py` completes successfully, resulting in the expected prompt.

**Comment by ZyX-I** [comment]
@cviner This means that the problem is with C code. To debug you will have to compile it yourself with `-O0 -g` in `CFLAGS`: it should be enough just to use `CFLAGS='-O0 -g' pip …` (`…` is your command to install powerline). Then the sequence

1. Hang one terminal using the bug in question.
2. In other terminal use `ps -C powerline` to get the PID of the hanged process.
3. Then running `gdb -p {hanged PID} -ex 'thread apply all bt full' -batch` should give the answer to the question where C code hang.

**Comment by cviner** [comment]
@ZyX-I Thanks for the detailed debugging instructions. It will be a while until I get to this; I will report the results once I have completed the outlined protocol.

**Comment by SoumenDass** [comment]
I can re-produce the exact steps for this bug:

http://pastebin.com/bVSLRFNG

It seems to be related to PYTHONPATH having current directory (.) as a member

**Comment by cviner** [comment]
I encounter this issue without having the current directory on my ```PYTHONPATH```.

**Comment by ramsey** [comment]
I just encountered this problem. I'm not sure what causes it, since I've been using my terminal configuration for years without this issue. I did not install or upgrade any software today. Rebooting my machine did not fix it.

I'm running:

* Mac OS X 10.11.6
* iTerm2, but I also experience this issue with Apple Terminal
* zsh 5.2 (Homebrew version)
* powerline-status 2.3.dev9999+git.d611cc2e439e02a123b4f208767c8dc5f72ce567

My shell configuration is available here: https://github.com/ramsey/dotfiles

I did noticed two things that I can do to work around the issue:

* Turn off wi-fi, launch terminal; prompt successfully appears, and I can turn wi-fi back on, or
* Comment out the following line in my `~/.zsh/config` file:

```
export POWERLINE_LOCATION=`pip show powerline-status | grep "^Location" | awk '{ print $2 }'`
```

The problem appears to be a network-related issue with `pip`. For example, when I type `pip show powerline-status`, I see:

    $ pip show powerline-status
    Name: powerline-status
    Version: 2.3.dev9999+git.d611cc2e439e02a123b4f208767c8dc5f72ce567
    Summary: The ultimate statusline/prompt utility.
    Home-page: https://github.com/powerline/powerline
    Author: Kim Silkebaekken
    Author-email: kim.silkebaekken+vim@gmail.com
    License: MIT
    Location: /usr/local/lib/python2.7/site-packages
    Requires:

And then it just hangs at that point. When I `Ctrl+c` to cancel, I receive the following backtrace:

<details>
    <summary>Python pip backtrace <em>(click to expand)</em></summary>

```
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==9.0.1', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 628, in send
    r.content
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/models.py", line 755, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/models.py", line 676, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 297, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 289, in set
    return super(SafeFileCache, self).set(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/caches/file_cache.py", line 99, in set
    with self.lock_class(name) as lock:
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/lockfile/__init__.py", line 197, in __enter__
    self.acquire()
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/lockfile/mkdirlockfile.py", line 57, in acquire
    time.sleep(wait)
KeyboardInterrupt
```

</details>


This may not be a problem with powerline at all but, rather, with some `pip` networking issue. It's frustrating, though.

**Comment by ramsey** [comment]
Curiouser and curiouser... If I switch to any virtualenv, pip works fine there, but when not in a virtualenv, pip hangs as described.

**Comment by ZyX-I** [comment]
@ramsey Problem with pip is definitely not a powerline problem. `pip` AFAIK should only periodically connect to the internet to check for updates (may be disabled by your distribution?), disabled with `--disable-pip-version-check`, otherwise it should not do any internet connections. Yet it always opens some IPv6 socket, including with this argument.

**Comment by ramsey** [comment]
Thanks. Using `--disable-pip-version-check` does the trick. Now, if I can just figure out what's going on with pip... :smile:

**Comment by ramsey** [comment]
A few more details, in case this helps others who find this issue on similar searches...

This issue appears to be related to caching, not network connections, as I originally thought. When I use `-vvv`, I can see that the command hangs when it tries caching the response:

<details>
<summary>Output of <code>pip show -vvv powerline-status</code></summary>

```
Name: powerline-status
Version: 2.3.dev9999+git.d611cc2e439e02a123b4f208767c8dc5f72ce567
Summary: The ultimate statusline/prompt utility.
Home-page: https://github.com/powerline/powerline
Author: Kim Silkebaekken
Author-email: kim.silkebaekken+vim@gmail.com
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires:
Metadata-Version: 1.1
Installer:
Classifiers:
  Development Status :: 4 - Beta
  Environment :: Console
  Environment :: Plugins
  Intended Audience :: End Users/Desktop
  License :: OSI Approved :: MIT License
  Natural Language :: English
  Operating System :: Microsoft :: Windows
  Operating System :: POSIX
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3.2
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: Implementation :: CPython
  Programming Language :: Python :: Implementation :: PyPy
Entry-points:
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 72986
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching b/c date exists and max-age > 0
```
</details>



Running the same command with `--no-cache` succeeds without any problems. This issue appears related: https://github.com/pypa/pip/issues/3245

It seems that, by clearing the cache directory, you can solve this problem. See also: http://stackoverflow.com/a/31807659/446932

Running `rm -rf ~/Library/Caches/pip` did the trick for me on OS X. Now, I can run `pip` commands without `--no-cache` or `--disable-pip-version-check`.

Best of luck!

**Comment by ZyX-I** [comment]
@afrankenthal What do you mean by “hang”? Based on what I see if you make too long directory it will not hang, it will just throw away all segments with priority lower then current directory segment (that is, *all* segments except for the current directory segment in default configuration as they either appear earlier or actually have lower priority) then throw away current directory segment too since it does not fit. Which leaves you with an *empty prompt* rather then *hanged prompt* and is actually an expected behaviour with default configuration, though still frustrating. What happens if prompt *hangs* you may see by setting PS1 to `$(sleep 10)`.

If you have many long directory names just copy shell theme to your local configuration directory, <s>remove all configuration except `segments` list from it (it will be loaded from default configuration)</s> (default and default_leftonly shell themes already have no other data) and remove priority key from segments you do not wish to disappear.

**Comment by mateuszzz88** [comment]
I have something similar. 
When I cd into directory, shell hangs. When I ctrl+c, I get following backtrace:
```
Traceback (most recent call last):
  File "/home1/mateuszl/.local/bin/powerline-shell", line 11, in <module>
    sys.exit(main())
  File "/home1/mateuszl/.local/lib/python2.7/site-packages/powerline_shell/__init__.py", line 240, in main
    segment.add_to_powerline()
  File "/home1/mateuszl/.local/lib/python2.7/site-packages/powerline_shell/segments/git.py", line 71, in add_to_powerline
    self.join()
  File "/usr/lib/python2.7/threading.py", line 940, in join
    self.__block.wait()
  File "/usr/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
``` 
and the hang continues. However after some timeout powerline renders correctly. Then can issue ls -l
```
total 1008
drwxrwxr-x 6 mateuszl mateuszl   4096 Jun 29 07:05 ./
drwxrwxr-x 5 mateuszl mateuszl   4096 Jun 25 10:18 ../
lrwxrwxrwx 1 mateuszl mateuszl     35 Jun  8 12:04 borg_keys -> ../../colony_scripts/fis/borg_keys//
lrwxrwxrwx 1 mateuszl mateuszl     51 Jan 28 15:05 BorgSystem.py -> ../../colony_scripts/horcrux/borgtype/BorgSystem.py*
drwxrwxr-x 3 mateuszl mateuszl   4096 Jun 29 07:05 colony_configs/
lrwxrwxrwx 1 mateuszl mateuszl     61 Apr  8 17:29 DurableMediaTest.py -> ../../colony_scripts/vui/testDurableMedia/DurableMediaTest.py*
drwxrwxr-x 2 mateuszl mateuszl   4096 Jun 29 07:09 execs/
lrwxrwxrwx 1 mateuszl mateuszl     50 Jun 25 10:18 extra_files -> ../../colony_scripts/horcrux/borgtype/extra_files//
-rwxrwxr-x 1 mateuszl mateuszl   2035 Jun 29 07:05 fetchLogs.py*
-rwxrwxr-x 1 mateuszl mateuszl  35046 Jun 29 07:05 fis_test3.py*
-rw-rw-r-- 1 mateuszl mateuszl    175 May 25 11:18 .gitignore
-rw-rw-r-- 1 mateuszl mateuszl 731101 Jun 10 09:54 logBorgsystem.txt
-rw-rw-r-- 1 mateuszl mateuszl   9396 Jun 22 14:13 logColonyTests.log
-rw-rw-r-- 1 mateuszl mateuszl  88623 May 25 12:06 nodes_colony.yaml
-rw-rw-r-- 1 mateuszl mateuszl   9641 Jun  4 09:01 private_config1.py
-rw-rw-r-- 1 mateuszl mateuszl   8160 Jun 22 12:33 private_config.py
lrwxrwxrwx 1 mateuszl mateuszl     59 Apr  2 08:08 private_config_va.py -> /home1/mateuszl/src/va/gitlab-ci.d/colony/private_config.py
-rw-rw-r-- 1 mateuszl mateuszl    276 Jun  4 09:01 private_do_all.sh
drwxrwxr-x 2 mateuszl mateuszl   4096 Jun 22 12:53 __pycache__/
-rw-rw-r-- 1 mateuszl mateuszl  40155 Jun  4 09:01 report_146-14-05-12
-rw-rw-r-- 1 mateuszl mateuszl   6004 Jun  4 09:01 report_146-14-06-23
-rw-rw-r-- 1 mateuszl mateuszl   1081 Jun  4 09:01 report_146-14-07-00
-rw-rw-r-- 1 mateuszl mateuszl   3161 Jun  4 09:01 report_146-14-10-15
-rw-rw-r-- 1 mateuszl mateuszl  38863 Jun 22 14:02 report_174-13-51-29
lrwxrwxrwx 1 mateuszl mateuszl     50 Apr 27 11:14 run_colony_tests.py -> ../../colony_scripts/vui/tests/run_colony_tests.py*
drwxrwxr-x 3 mateuszl mateuszl   4096 Jun 29 07:05 test_configs/
lrwxrwxrwx 1 mateuszl mateuszl     37 Jan 28 15:05 vui.py -> ../../colony_scripts/vui/tests/vui.py
```
and hang again. `cd`ing into subdirectory of this has the same effect.
My config:
```
cat .config/powerline-shell/config.json 
{  "segments": [
          "time",
    "virtual_env", 
    "hostname", 
    "cwd", 
    "git", 
    "hg", 
    "jobs", 
    "root"
  ]
}
```
Version:
```
powerline-shell==0.7.0
```

This may be incidental, but:
* on normal day I can use powerline in this directory no problem
* today it started right after I copied 2 large files (>4GB) to symlink/subdirectory (`extra_files -> ../../colony_scripts/horcrux/borgtype/extra_files//` from network volume.
* I recall that more than once I had problems with hanging shell after copying large files from network, but never before associated it with powerline. I also don't recall previous hangs time-outing, so this may be separate and/or related issue.

**Comment by PH111P** [comment]
> I have something similar.
> When I cd into directory, shell hangs. When I ctrl+c, I get following backtrace:
> 
> ```
> Traceback (most recent call last):
>   File "/home1/mateuszl/.local/bin/powerline-shell", line 11, in <module>
>     sys.exit(main())
>   File "/home1/mateuszl/.local/lib/python2.7/site-packages/powerline_shell/__init__.py", line 240, in main
>     segment.add_to_powerline()
>   File "/home1/mateuszl/.local/lib/python2.7/site-packages/powerline_shell/segments/git.py", line 71, in add_to_powerline
>     self.join()
>   File "/usr/lib/python2.7/threading.py", line 940, in join
>     self.__block.wait()
>   File "/usr/lib/python2.7/threading.py", line 340, in wait
>     waiter.acquire()
> KeyboardInterrupt
> ```
> 
> and the hang continues. However after some timeout powerline renders correctly. Then can issue ls -l
> 
> ```
> total 1008
> drwxrwxr-x 6 mateuszl mateuszl   4096 Jun 29 07:05 ./
> drwxrwxr-x 5 mateuszl mateuszl   4096 Jun 25 10:18 ../
> lrwxrwxrwx 1 mateuszl mateuszl     35 Jun  8 12:04 borg_keys -> ../../colony_scripts/fis/borg_keys//
> lrwxrwxrwx 1 mateuszl mateuszl     51 Jan 28 15:05 BorgSystem.py -> ../../colony_scripts/horcrux/borgtype/BorgSystem.py*
> drwxrwxr-x 3 mateuszl mateuszl   4096 Jun 29 07:05 colony_configs/
> lrwxrwxrwx 1 mateuszl mateuszl     61 Apr  8 17:29 DurableMediaTest.py -> ../../colony_scripts/vui/testDurableMedia/DurableMediaTest.py*
> drwxrwxr-x 2 mateuszl mateuszl   4096 Jun 29 07:09 execs/
> lrwxrwxrwx 1 mateuszl mateuszl     50 Jun 25 10:18 extra_files -> ../../colony_scripts/horcrux/borgtype/extra_files//
> -rwxrwxr-x 1 mateuszl mateuszl   2035 Jun 29 07:05 fetchLogs.py*
> -rwxrwxr-x 1 mateuszl mateuszl  35046 Jun 29 07:05 fis_test3.py*
> -rw-rw-r-- 1 mateuszl mateuszl    175 May 25 11:18 .gitignore
> -rw-rw-r-- 1 mateuszl mateuszl 731101 Jun 10 09:54 logBorgsystem.txt
> -rw-rw-r-- 1 mateuszl mateuszl   9396 Jun 22 14:13 logColonyTests.log
> -rw-rw-r-- 1 mateuszl mateuszl  88623 May 25 12:06 nodes_colony.yaml
> -rw-rw-r-- 1 mateuszl mateuszl   9641 Jun  4 09:01 private_config1.py
> -rw-rw-r-- 1 mateuszl mateuszl   8160 Jun 22 12:33 private_config.py
> lrwxrwxrwx 1 mateuszl mateuszl     59 Apr  2 08:08 private_config_va.py -> /home1/mateuszl/src/va/gitlab-ci.d/colony/private_config.py
> -rw-rw-r-- 1 mateuszl mateuszl    276 Jun  4 09:01 private_do_all.sh
> drwxrwxr-x 2 mateuszl mateuszl   4096 Jun 22 12:53 __pycache__/
> -rw-rw-r-- 1 mateuszl mateuszl  40155 Jun  4 09:01 report_146-14-05-12
> -rw-rw-r-- 1 mateuszl mateuszl   6004 Jun  4 09:01 report_146-14-06-23
> -rw-rw-r-- 1 mateuszl mateuszl   1081 Jun  4 09:01 report_146-14-07-00
> -rw-rw-r-- 1 mateuszl mateuszl   3161 Jun  4 09:01 report_146-14-10-15
> -rw-rw-r-- 1 mateuszl mateuszl  38863 Jun 22 14:02 report_174-13-51-29
> lrwxrwxrwx 1 mateuszl mateuszl     50 Apr 27 11:14 run_colony_tests.py -> ../../colony_scripts/vui/tests/run_colony_tests.py*
> drwxrwxr-x 3 mateuszl mateuszl   4096 Jun 29 07:05 test_configs/
> lrwxrwxrwx 1 mateuszl mateuszl     37 Jan 28 15:05 vui.py -> ../../colony_scripts/vui/tests/vui.py
> ```
> 
> and hang again. `cd`ing into subdirectory of this has the same effect.
> My config:
> 
> ```
> cat .config/powerline-shell/config.json 
> {  "segments": [
>           "time",
>     "virtual_env", 
>     "hostname", 
>     "cwd", 
>     "git", 
>     "hg", 
>     "jobs", 
>     "root"
>   ]
> }
> ```
> 
> Version:
> 
> ```
> powerline-shell==0.7.0
> ```
> 
> This may be incidental, but:
> 
> * on normal day I can use powerline in this directory no problem
> * today it started right after I copied 2 large files (>4GB) to symlink/subdirectory (`extra_files -> ../../colony_scripts/horcrux/borgtype/extra_files//` from network volume.
> * I recall that more than once I had problems with hanging shell after copying large files from network, but never before associated it with powerline. I also don't recall previous hangs time-outing, so this may be separate and/or related issue.

I'm sorry, but it seems as if you are not using `powerline`, but the unrelated `powerline-shell` (https://github.com/b-ryan/powerline-shell).
