### ISSUE TITLE
Not work custom segment in ~/.config/powerline/segments/

### ISSUE THREAD

**Issue by khmelevskii** [powerline/powerline#151]
if I write in file `~/.config/powerline/themes/vim/my.json` this

``` json
...
{
    "name": "elapsedtime",
        "module": "powerline.segments.my",
    "priority": 60,
    "rjust": 4
},
...
```

and then create file `~/.config/powerline/segments/my.py` with content

``` python
# -*- coding: utf-8 -*-

from __future__ import absolute_import

import vim

def elapsedtime():
  try:
    return vim.eval('TimeKeeper_GetCurrentJobString()')
  except vim.error:
    return None
```

I have got errors

```
Error detected while processing /Users/khmelevskii/.vim/bundle/powerline/powerline/bindings/vim/powerline.vim:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/khmelevskii/.vim/bundle/powerline/powerline/core.py", line 50, in __init__
    term_24bit_colors=self.config.get('term_24bit_colors', False))
  File "/Users/khmelevskii/.vim/bundle/powerline/powerline/renderers/vim.py", line 21, in __init__
    super(VimRenderer, self).__init__(*args, **kwargs)
  File "/Users/khmelevskii/.vim/bundle/powerline/powerline/renderer.py", line 15, in __init__
    self.theme = Theme(theme_config=theme_config, **theme_kwargs)
  File "/Users/khmelevskii/.vim/bundle/powerline/powerline/theme.py", line 28, in __init__
    self.segments[side].extend((get_segment(segment, side) for segment in theme_config['segments'].get(side, [])))
  File "/Users/khmelevskii/.vim/bundle/powerline/powerline/theme.py", line 28, in <genexpr>
    self.segments[side].extend((get_segment(segment, side) for segment in theme_config['segments'].get(side, [])))
  File "/Users/khmelevskii/.vim/bundle/powerline/powerline/segment.py", line 36, in get
    contents, contents_func, key = get_segment_info(segment)
  File "/Users/khmelevskii/.vim/bundle/powerline/powerline/segment.py", line 18, in get_function
    return None, getattr(import_module(segment_module), segment['name']), '{0}.{1}'.format(segment_module, segment['name'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named my
```

if I copy `~/.config/powerline/segments/my.py` into `~/.vim/bundle/powerline/powerline/segments/` everything works fine.

what am I doing wrong?

**Comment by joedaniels29** [comment]
Should This example work? If I do just this, should it work? or is something missing from here. I am trying to write a hello world segment, and I'm not understanding how to make it work. is there any example/docs on how to configure a basic extension?

**Comment by varac** [comment]
I'm also missing a hello world example for powerline.
