### ISSUE TITLE
No module named 'packaging' or 'pkg_resources._vendor' when installing on Python 3

### ISSUE THREAD

**Issue by s0r00t** [powerline/powerline#1515]
When installing `powerline-status` from PyPi via the AUR Python 3 package or `pip install --user`, the installation fails with this traceback : 
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 91, in <module>
    import pkg_resources._vendor.packaging.version
ImportError: No module named 'pkg_resources._vendor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 97, in <module>
    import packaging.version
ImportError: No module named 'packaging'
```

I'm running Python 3.5.1 on Arch Linux x64.

**Comment by s0r00t** [comment]
It was an issue with the `python-pip` package provided on Arch.
Sorry for the 'fast-reporting'. Closing.
