### ISSUE TITLE
Unable to locate sites-enabled/scripts folder for zsh

### ISSUE THREAD

**Issue by rjrobinson** [powerline/powerline#1536]
So i installed the power line, and I am getting an error. 

When i try and `source "/Library/Python/2.7/site-packages/powerline/bindings/zsh/powerline.zsh"`

Im getting an error for unk directory. 

its not there. Im curious if I installed it wrong, or if this is a bug.

**Comment by ZyX-I** [comment]
You need to copy error here. And most likely you simply installed powerline for one Python, but are trying to use from another, Mac OS may have two python versions: installed by brew and system Python.

**Comment by rjrobinson** [comment]
I tried to start over and now Im getting this error. 

```$ sudo pip install powerline-status
The directory '/Users/rrobin008c/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/rrobin008c/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting powerline-status
Installing collected packages: powerline-status
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 731, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 845, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1044, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 375, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 321, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/bin/powerline'```

**Comment by rjrobinson** [comment]
If it helps... 

```
 $which python
/usr/bin/python
```
python 2.7

**Comment by ZyX-I** [comment]
@rjrobinson To format code you must place <code>```</code> on its own line.

**Comment by rjrobinson** [comment]
done. :)

**Comment by ZyX-I** [comment]
@rjrobinson Read first line of the output. Though this is not the problem from the first message, it is something related to wheel and I have no idea why.

**Comment by ZyX-I** [comment]
Maybe removing powerline-status first will help with this specific error.

**Comment by rjrobinson** [comment]
lol. dont even know what that means. 
 However, it still looks as if it did isntall... But when i try to source the zsh binding, i get 
```
powerline/bindings/zsh/powerline.zsh:200: no such file or directory: /Library/Python/2.7/site-packages/scripts/powerline-config
powerline/bindings/zsh/powerline.zsh:204: no such file or directory: /Library/Python/2.7/site-packages/scripts/powerline-config
```

There is still no scripts folder at all.

**Comment by rjrobinson** [comment]
Like. `scripts/powerline-config` does not exist. Do I have to create this?

**Comment by ZyX-I** [comment]
@rjrobinson `powerline-config` must be found in your `$PATH`. pip installed it somewhere else and that “somewhere else” is not in your `$PATH`, so `powerline.zsh` assumes that you have `--editable` installation (i.e. cloned repository, not `pip` installation).

**Comment by ZyX-I** [comment]
You must modify `$PATH` before sourcing powerline bindings, not create that file.

**Comment by ZyX-I** [comment]
Duplicate of #1479 and maybe some other issue.

**Comment by rjrobinson** [comment]
Yea. Thought the same. I added `export PATH="$PATH:$HOME/Library/Python/2.7/bin"
` to my zsh file.

**Comment by rjrobinson** [comment]
Im not really sure where to go from here. Its in my path. I just unionstalled it again. I though that maybe because i ran it as root, it did that odd install issue. 

```
$ pip install powerline-status
Collecting powerline-status
Installing collected packages: powerline-status
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 731, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 845, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1044, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 343, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 314, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 82, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/powerline'
```

so __NOW__ Im getting this error w/o sudo. IDK what this wheel.py thing is either. could you point me to a different tutorial that could help me. :(

**Comment by rjrobinson** [comment]
If I run sudo i get 
```
$ sudo pip install powerline-status
The directory '/Users/rrobin008c/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/rrobin008c/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting powerline-status
Installing collected packages: powerline-status
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 731, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 845, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1044, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 375, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 321, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/bin/powerline'
```

**Comment by rjrobinson** [comment]
It does install, but im guessing only partially
because 
```
$ ls
... powerline_status-2.3.dist-info powerline ...
```

**Comment by rjrobinson** [comment]
do I have to add `--user` ?

**Comment by ZyX-I** [comment]
@rjrobinson I do not have Mac OS. I only know that for some Python you cannot install *without* --user and for some you cannot install *with* --user. Or something like this. Better go to IRC (freenode), `#python` or `#mac` and ask there.

And why do you run `sudo` again if first line of the message explicitly asked about `sudo -H`?

**Comment by ZyX-I** [comment]
According to #1479 path is likely to look something like `/Library/Python/2.7/bin`.

**Comment by ZyX-I** [comment]
If using system Python. Or `/Users/{user}/Library/Python/2.7/bin` for brew(?).

**Comment by rjrobinson** [comment]
Sorry about the other ticket. 
So, i somehow got it working, but is the right nitifier supposed to be off the screen like that. I have supplied a screen shot. 

https://dl.dropboxusercontent.com/u/9377605/Screen%20Shot%202016-03-02%20at%2010.58.38%20AM.png
