### ISSUE TITLE
Cannot install with instructions provided. 

### ISSUE THREAD

**Issue by rjrobinson** [powerline/powerline#1537]
Hey guy. I reset my path. i have reinstalled pip. I have done all that I can Could you please not just close the issue when the issue still exists. 

I have installed pip from scratch, and then ran ` pip install powerline-status ` 

I got an error that read 

```
$ pip install powerline-status
Collecting powerline-status
Installing collected packages: powerline-status
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 731, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 845, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1044, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 343, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 314, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 82, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/powerline'
```

I'm not sure if the last part is important The OSError...

Then I tried to install via `sudo` and got this. 

```
$ sudo pip install powerline-status
The directory '/Users/rrobin008c/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/rrobin008c/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting powerline-status
Installing collected packages: powerline-status
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 731, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 845, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1044, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 375, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 321, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/bin/powerline'
```
While this did result in an error, I noticed that teh `powerline` directory was created. 

I made sure to export my path to include PIP and Python
currently `powerline` path is `/Library/Python/2.7/site-packages/powerline`

and I have exported the path into 
`export PATH="$PATH:$HOME/Library/Python/2.7/site-packages"`

What am I doing wrong exactly?

**Comment by rjrobinson** [comment]
my current path
```
/Users/rrobin008c/.nvm/versions/node/v0.12.7/bin:/Users/rrobin008c/.rvm/gems/ruby-2.2.3/bin:/Users/rrobin008c/.rvm/gems/ruby-2.2.3@global/bin:/Users/rrobin008c/.rvm/rubies/ruby-2.2.3/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:.:/Users/rrobin008c/.dotfiles/scripts:/bin:/bin:/opt/chef/bin:/opt/chef/embedded/bin:/usr/local/zend/bin:/usr/local/zend/mysql/bin:/usr/local/share/npm/bin:/usr/local/opt/go/libexec/bin:/Users/rrobin008c/.rvm/bin:bin/subl:/Applications/Postgres.app/Contents/Versions/9.4/bin:/Users/rrobin008c/Dropbox/Otto:/Users/rrobin008c/Library/Python/2.7/bin:/usr/local/sbin:bin/subl:/Applications/Postgres.app/Contents/Versions/9.4/bin:/Users/rrobin008c/Dropbox/Otto:/Users/rrobin008c/Library/Python/2.7:/usr/local/sbin:bin/subl:/Applications/Postgres.app/Contents/Versions/9.4/bin:/Users/rrobin008c/Dropbox/Otto:/Users/rrobin008c/Library/Python/:/usr/local/sbin:bin/subl:/Applications/Postgres.app/Contents/Versions/9.4/bin:/usr/local/sbin:bin/subl:/Applications/Postgres.app/Contents/Versions/9.4/bin:/usr/local/sbin:bin/subl:/Users/rrobin008c/.nvm/versions/node/v0.12.7/bin/node:/Applications/Postgres.app/Contents/Versions/9.4/bin:/Users/rrobin008c/Library/Python/2.7/site-packages:/usr/local/sbin
```

**Comment by ZyX-I** [comment]
site-packages is not a correct $PATH entry, you must find where pip installs *executables*, this is path for Python *modules*. AFAIR the issue I referenced had explicit path. Also it is very much unlikely that you can install both without `sudo` and `--user`.

Also installation instructions written for OS X explicitly require you use `pip install --user` when using system Python and `pip install` when using brew Python. So you are not following them.

**Comment by ZyX-I** [comment]
I also do not stop commenting on issues when they are closed, and there is no need to keep an issue open which is not an issue with powerline. All replies to the previous issue.
