### ISSUE TITLE
Powerline does not show up on tmux 2.2

### ISSUE THREAD

**Issue by nafizh** [powerline/powerline#1601]
I was using tmux 1.8 and powerline was working fine. Then I upgraded to tmux 2.2 and, now instead of the powerline bar only the default green bar shows up on my Mac OsX (El Capitan - Version 10.11.4).

If I write on the command line - `powerline-config tmux setup` the following errors show up -

```
Traceback (most recent call last):
  File "/Users/Nafiz/anaconda/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/Users/Nafiz/anaconda/lib/python2.7/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/Users/Nafiz/anaconda/lib/python2.7/site-packages/powerline/bindings/config.py", line 181, in tmux_setup
    tmux_version = get_tmux_version(pl)
  File "/Users/Nafiz/anaconda/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 76, in get_tmux_version
    version_string = get_tmux_output(pl, '-V')
  File "/Users/Nafiz/anaconda/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 37, in get_tmux_output
    return _run_tmux(lambda cmd: run_cmd(pl, cmd), args)
  File "/Users/Nafiz/anaconda/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 27, in _run_tmux
    return runner([get_tmux_executable_name()] + list(args))
  File "/Users/Nafiz/anaconda/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 37, in <lambda>
    return _run_tmux(lambda cmd: run_cmd(pl, cmd), args)
  File "/Users/Nafiz/anaconda/lib/python2.7/site-packages/powerline/lib/shell.py", line 34, in run_cmd
    p = Popen(cmd, shell=False, stdout=PIPE, stdin=PIPE)
  File "/Users/Nafiz/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/Nafiz/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

My `.tmux.config` file has the following-

```
run-shell "powerline-daemon -q"

source "/Users/Nafiz/anaconda/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"


# use 256 colors
set -g default-terminal "screen-256color"
```

Any help will be appreciated.

**Comment by BlitzKraft** [comment]
Could you attach the output of `powerline tmux left` and `powerline tmux right`?

**Comment by ZyX-I** [comment]
What locale are you running `powerline-config tmux setup` in?

**Comment by nafizh** [comment]
Hi, I solved the problem with some hacking but here are the outputs before that-

for `powerline tmux left` - nothing happens.
for `powerline tmux right` the output is -

`#[fg=colour233,bg=default,nobold,noitalics,nounderscore]  [fg=colour247,bg=colour233,nobold,noitalics,nounderscore] ⇑  12m 40s#[fg=colour241,bg=colour233,nobold,noitalics,nounderscore] #[fg=colour2,bg=colour233,nobold,noitalics,nounderscore] 1.6 #[fg=colour2,bg=colour233,nobold,noitalics,nounderscore]2.4 #[fg=colour2,bg=colour233,nobold,noitalics,nounderscore]2.4#[fg=colour236,bg=colour233,nobold,noitalics,nounderscore] #[fg=colour247,bg=colour236,nobold,noitalics,nounderscore] 2016-05-16#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore] #[fg=colour252,bg=colour236,bold,noitalics,nounderscore] ⌚ 22:43#[fg=colour252,bg=colour236,nobold,noitalics,nounderscore] #[fg=colour16,bg=colour252,bold,noitalics,nounderscore]  nafiz-unix.local`

But I solved the problem by adding the following lines to the `/Users/Nafiz/anaconda/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py` file : 

```python
import sys

reload(sys)
sys.setdefaultencoding('utf8')
```

It's something I am afraid will break the code in the future. But for now it is a solution. The idea came from the error that I posted previously.

**Comment by ZyX-I** [comment]
Usually such errors are either because locale is invalid or there is an unexpected unicode string somewhere. Specifically *this* error may be raised when trying to decode raw bytes into a unicode string and I see exactly no reason in this stack trace to perform this decoding: last frame prints decode error dumped when reading output from spawned process (since it does `execvp[e]` this obviously means that it failed before executing `execvp[e]` or during executing this). In this place the only things which are controlled by my code are executable name (taken from your environment, defaults to `tmux`, so I guess unless you have POWERLINE_TMUX_EXE environment variable it will not ever be non-ASCII) and arguments (`-V`, always ASCII). And *none* of them need *decoding*, in fact it is needed to *encode* unicode strings to bytes.

I have only one suggestion: error happened when running `execvp`, when trying to create exception out of the error. But that means that your trick should not work: in place of getting decode error you would get real exception which does not seem to happen. I would suggest checking what happens if you run `powerline-config tmux setup` in `en_US.UTF-8` locale. At least, this should get rid of this exact error *assuming*  it is because of `strerror()` messages (libc function used to get error message out of the error code, message is locale-dependent).

**Comment by ZyX-I** [comment]
And your fix should not break my code. Though I am not sure what `reload(sys)` is doing there (and whether it is going to have any effect at all).

**Comment by nafizh** [comment]
So, the error that I posted, at that time when I wrote `echo $LANG`, the output was

`en_US.UTF-8`

**Comment by philbert** [comment]
I just upgraded to tmux 2.2 via homebrew and discovered that powerline did not display.
All I had to do was upgrade powerline to 2.4 via pip and it seems to be back to normal now.

**Comment by kierun** [comment]
On CentOS 7, Fedora 24, and  Ubuntu 14.04.4 LTS (Trusty Tahr) using powerline-status 2.4 and tmux 2.2 work fine with me with a custom configuration.

**Comment by bennypowers** [comment]
I solved this by adding the following to my init.fish

```fish
 set -x LANG en_US.UTF-8
 set -x LC_COLLATE en_US.UTF-8
 set -x LC_CTYPE en_US.UTF-8
 set -x LC_MESSAGES en_US.UTF-8
 set -x LC_MONETARY en_US.UTF-8
 set -x LC_NUMERIC en_US.UTF-8
 set -x LC_TIME en_US.UTF-8
 set -x LC_ALL en_US.UTF-8
```

YMMV

**Comment by revelationnow** [comment]
What worked for me, was that I had the tmux compiled from the master branch and the version number wasn't getting picked up by powerline. I had to edit the __init__.py file to override the version numbers.
def get_tmux_version(pl):
        version_string = get_tmux_output(pl, '-V')
        _, version_string = version_string.split(' ')
        version_string = version_string.strip()
        major = '2'
        minor = '4'
        suffix = DIGITS.subn('', minor)[0] or None
        minor = NON_DIGITS.subn('', minor)[0]
        return TmuxVersionInfo(int(major), int(minor), suffix)
