### ISSUE TITLE
Powerline doesn't work with IPython 5.x

### ISSUE THREAD

**Issue by ppsx** [powerline/powerline#1617]
Just after run ipython one can see this:

```python
[TerminalIPythonApp] WARNING | Error in loading extension: powerline.bindings.ipython.post_0_11
Check your config files in /home/local/GER/psocha/.ipython/profile_default
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/shellapp.py", line 246, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/extensions.py", line 83, in load_extension
    __import__(module_str)
  File "/usr/local/lib/python2.7/dist-packages/powerline/bindings/ipython/post_0_11.py", line 6, in <module>
    from IPython.core.prompts import PromptManager
ImportError: cannot import name PromptManager
```

Quick grep through IPython sources shows:

```python
        if 'PromptManager' in self.config:
            warn('As of IPython 5.0 `PromptManager` config will have no effect'
                 ' and has been replaced by TerminalInteractiveShell.prompts_class')
```

**Comment by ZyX-I** [comment]
It looks like they use pygments for highlighting their prompt as well. This is going to be tricky.

**Comment by ppsx** [comment]
Sounds like a real challenge...

**Comment by ppsx** [comment]
Aparently not a challenge for you :)
Respect.
