### ISSUE TITLE
Powerline is not working with tmux 2.2

### ISSUE THREAD

**Issue by cpanato** [powerline/powerline#1629]
Tmux version: 2.2
powerline version: 2.5

I added the configs in my tmux.conf
```
run-shell 'powerline-daemon -q'
source '/usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf'
```
and when reload the the conf I got:
```
'powerline-daemon -q' returned 1
'powerline-config tmux setup' returned 1
```

running powerline-daemon -q in the command line I got:
```

Traceback (most recent call last):
  File "/usr/local/bin/powerline-daemon", line 18, in <module>
    from powerline.commands.main import finish_args, write_output
  File "/usr/local/lib/python2.7/site-packages/powerline/commands/main.py", line 17, in <module>
    encoding = get_preferred_arguments_encoding()
  File "/usr/local/lib/python2.7/site-packages/powerline/lib/encoding.py", line 89, in get_preferred_arguments_encoding
    locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

my locale are:
```
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

any tips?

**Comment by ZyX-I** [comment]
`UTF-8` is not a valid LC_CTYPE value. There are some predefined values like `C` or `POSIX`, otherwise it is expected to be something like `en_US.UTF-8`.

If you think that your LC_CTYPE value is correct, file a bug report to the *python* project with a stack trace of `python -c 'import locale; locale.getdefaultlocale()'` with the same environment.
