### ISSUE TITLE
VCS module doesn't know about is_watching()

### ISSUE THREAD

**Issue by gladiac** [powerline/powerline#1640]
This happens on openSUSE 42.1 with python 2.7.12:

```

python -c 'from powerline.lib.vcs import debug; debug()' $(pwd)
Watching /home/asn/workspace/projects/samba
Press Ctrl-C to exit.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/powerline/lib/vcs/__init__.py", line 269, in debug
    print ('Branch name: %s Status: %s' % (repo.branch(), repo.status()))
  File "/usr/lib/python2.7/site-packages/powerline/lib/vcs/git.py", line 93, in branch
    create_watcher=self.create_watcher,
  File "/usr/lib/python2.7/site-packages/powerline/lib/vcs/__init__.py", line 58, in get_branch_name
    is_watched = fw.is_watching(directory)
AttributeError: 'functools.partial' object has no attribute 'is_watching'
```

**Comment by gladiac** [comment]
powerline version 2.5
