### ISSUE TITLE
Powerline fails to know about custom Mercurial extensions

### ISSUE THREAD

**Issue by BobobUnicorn** [powerline/powerline#1646]
When I start vim + powerline in a Mercurial repo and open a file, I get the following error message:

```
*** failed to import extension xxx: No module named xxx                                                                                                                          
2016-09-13 16:01:30,548:ERROR:vim:file_vcs_status:Exception while computing segment: repository requires features unknown to this Mercurial: xxx                                              
Traceback (most recent call last):                                                                                                                                                            
  File "/usr/local/lib/python2.7/dist-packages/powerline/segment.py", line 173, in process_segment                                                                                            
    contents = segment['contents_func'](pl, segment_info)                                                                                                                                     
  File "/usr/local/lib/python2.7/dist-packages/powerline/segment.py", line 412, in <lambda>                                                                                                   
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, segment_info=segment_info, **args)                                                                                         
  File "/usr/local/lib/python2.7/dist-packages/powerline/segments/vim/__init__.py", line 544, in file_vcs_status                                                                              
    status = repo.status(os.path.relpath(name, repo.directory))                                                                                                                               
  File "/usr/local/lib/python2.7/dist-packages/powerline/lib/vcs/mercurial.py", line 59, in status                                                                                            
    create_watcher=self.create_watcher,                                                                                                                                                       
  File "/usr/local/lib/python2.7/dist-packages/powerline/lib/vcs/__init__.py", line 131, in get_file_status                                                                                   
    file_status_cache[keypath] = ans = get_func(directory, file_path)                                                                                                                         
  File "/usr/local/lib/python2.7/dist-packages/powerline/lib/vcs/mercurial.py", line 64, in do_status                                                                                         
    repo = self._repo(directory)                                                                                                                                                              
  File "/usr/local/lib/python2.7/dist-packages/powerline/lib/vcs/mercurial.py", line 37, in _repo                                                                                             
    return hg.repository(self.ui, directory)                                                                                                                                                  
  File "/usr/lib/python2.7/dist-packages/mercurial/hg.py", line 165, in repository                                                                                                            
    peer = _peerorrepo(ui, path, create)                                                                                                                                                      
  File "/usr/lib/python2.7/dist-packages/mercurial/hg.py", line 152, in _peerorrepo                                                                                                           
    obj = _peerlookup(path).instance(ui, path, create)                                                                                                                                        
  File "/usr/lib/python2.7/dist-packages/mercurial/localrepo.py", line 1957, in instance                                                                                                      
    return localrepository(ui, util.urllocalpath(path), create)                                                                                                                               
  File "/usr/lib/python2.7/dist-packages/mercurial/localrepo.py", line 306, in __init__                                                                                                       
    self.vfs, self.supported)                                                                                                                                                                 
  File "/usr/lib/python2.7/dist-packages/mercurial/scmutil.py", line 1111, in readrequires                                                                                                    
    hint=_("see https://mercurial-scm.org/wiki/MissingRequirement"                                                                                                                            
RequirementError: repository requires features unknown to this Mercurial: xxx    
```

I believe this is because powerline uses [MercurialApi](https://www.mercurial-scm.org/wiki/MercurialApi) instead of [CommandServer](https://www.mercurial-scm.org/wiki/CommandServer).

**Comment by BobobUnicorn** [comment]
Thanks everyone!
