### ISSUE TITLE
neovim + python 3.5.2 (AttributeError: 'str' object has no attribute 'decode')

### ISSUE THREAD

**Issue by qwexvf** [powerline/powerline#1689]
Hi there!
does powerline for vim(neovim) supports python 3.5.2 ?

i have this easy issue.

```
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/powerline/vim.py", line 15, in <module>
    from powerline.bindings.vim import vim_get_func, vim_getvar, get_vim_encoding, python_to_vim
  File "/usr/local/lib/python3.5/site-packages/powerline/bindings/vim/__init__.py", line 44, in <module>
    vim_encoding = get_vim_encoding()
  File "/usr/local/lib/python3.5/site-packages/powerline/bindings/vim/__init__.py", line 25, in get_vim_encoding
    return vim.options['encoding'].decode('ascii') or 'ascii'
AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined
```

if theres already a fix please! if not i could fix it and make a pull request. thanks.

**Comment by ZyX-I** [comment]
Powerline does not support Neovim now.

**Comment by qwexvf** [comment]
@ZyX-I i see! thank you.
