### ISSUE TITLE
Powerline doesn't work with IPython 5.2.0 (and Python 3.6.0)

### ISSUE THREAD

**Issue by fgimian** [powerline/powerline#1709]
Hey there folks, I'm afraid that Powerline is no longer happy with the very latest version of IPython

```
 fots  ~  ipython
Python 3.6.0 (default, Dec 24 2016, 00:01:50) 
Type "copyright", "credits" or "license" for more information.

IPython 5.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
[TerminalIPythonApp] WARNING | Error in loading extension: powerline.bindings.ipython.post_0_11
Check your config files in /Users/fots/.ipython/profile_default
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/IPython/core/shellapp.py", line 246, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/usr/local/lib/python3.6/site-packages/IPython/core/extensions.py", line 85, in load_extension
    if self._call_load_ipython_extension(mod):
  File "/usr/local/lib/python3.6/site-packages/IPython/core/extensions.py", line 132, in _call_load_ipython_extension
    mod.load_ipython_extension(self.shell)
  File "/usr/local/lib/python3.6/site-packages/powerline/bindings/ipython/post_0_11.py", line 111, in load_ipython_extension
    ip.prompts = PowerlinePrompts(ip)
  File "/usr/local/lib/python3.6/site-packages/powerline/bindings/ipython/since_5.py", line 62, in __init__
    powerline.do_setup(shell, self, shutdown_hook)
  File "/usr/local/lib/python3.6/site-packages/powerline/bindings/ipython/since_5.py", line 26, in do_setup
    saved_msfn = ip._make_style_from_name
AttributeError: 'TerminalInteractiveShell' object has no attribute '_make_style_from_name'

In [1]: 
```

IPython 5.1.0 works just fine on the same system.

```
 fots  ~  ipython
Python 3.6.0 (default, Dec 24 2016, 00:01:50) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

 In [1]   
```

Thanks in advance for your help!

Cheers
Fotis

**Comment by fgimian** [comment]
In case it's useful, my IPython config looks like this:

```python
c = get_config()

c.InteractiveShellApp.extensions = [
    'powerline.bindings.ipython.post_0_11'
]
c.TerminalInteractiveShell.confirm_exit = False
```

**Comment by ppsx** [comment]
Again broken backward compatibility in IPython... The same situation was for IPython 5.0.
I confirm this issue also for Python 2.7.

**Comment by fgimian** [comment]
I can confirm this is now working perfectly, thanks! 😄
