### ISSUE TITLE
KeyError when typing in insert mode (Vim 8.0)

### ISSUE THREAD

**Issue by alexcoplan** [powerline/powerline#1715]
I've recently upgraded my Vim. `vim --version` displays this:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  3 2017 19:09:12)
MacOS X (unix) version
Included patches: 1-297
Compiled by Homebrew
...
```

When I edit a file where YouCompleteMe is enabled and start typing in insert mode, I get the following error from Powerline:

```
2017-02-06 13:10:51,654:ERROR:vim:mode:Exception while computing segment: u'ic'
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/powerline/segment.py", line 173, in process_segment
    contents = segment['contents_func'](pl, segment_info)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/powerline/segment.py", line 412, in <lambda>
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, segment_info=segment_info, **args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/powerline/segments/vim/__init__.py", line 101, in mode
    return vim_modes[mode]
KeyError: u'ic'
```

it seems like Vim is in a mode which powerline doesn't recognise? If anyone has any advice I would be really appreciative!

**Comment by alexcoplan** [comment]
Thanks for looking into this: any update so far? Can I help with the patch?

**Comment by ZyX-I** [comment]
@alexcoplan No, tests fail for an unrelated reason.
