### ISSUE TITLE
locale.getdefaultlocale()[1] returns 'UTF-8' on OSX

### ISSUE THREAD

**Issue by Industrial** [powerline/powerline#1777]
Hi.

I'm getting this error:

```
Traceback (most recent call last):
  File "/Users/twieland/Library/Python/2.7/bin/powerline-config", line 6, in <module>
    from powerline.commands.config import get_argparser
  File "/Users/twieland/Library/Python/2.7/lib/python/site-packages/powerline/commands/config.py", line 6, in <module>
    import powerline.bindings.config as config
  File "/Users/twieland/Library/Python/2.7/lib/python/site-packages/powerline/bindings/config.py", line 19, in <module>
    from powerline.commands.main import finish_args
  File "/Users/twieland/Library/Python/2.7/lib/python/site-packages/powerline/commands/main.py", line 18, in <module>
    encoding = get_preferred_arguments_encoding()
  File "/Users/twieland/Library/Python/2.7/lib/python/site-packages/powerline/lib/encoding.py", line 89, in get_preferred_arguments_encoding
    locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Traceback (most recent call last):
  File "/Users/twieland/Library/Python/2.7/bin/powerline-config", line 6, in <module>
    from powerline.commands.config import get_argparser
  File "/Users/twieland/Library/Python/2.7/lib/python/site-packages/powerline/commands/config.py", line 6, in <module>
    import powerline.bindings.config as config
  File "/Users/twieland/Library/Python/2.7/lib/python/site-packages/powerline/bindings/config.py", line 19, in <module>
    from powerline.commands.main import finish_args
  File "/Users/twieland/Library/Python/2.7/lib/python/site-packages/powerline/commands/main.py", line 18, in <module>
    encoding = get_preferred_arguments_encoding()
  File "/Users/twieland/Library/Python/2.7/lib/python/site-packages/powerline/lib/encoding.py", line 89, in get_preferred_arguments_encoding
    locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by ZyX-I** [comment]
You have invalid locale setting, check `locale` output: `UTF-8` is not a valid locale, it must be something like `en_US.UTF-8`.

**Comment by Industrial** [comment]
This s correct. I needed to load powerline later.
