### ISSUE TITLE
Unable to find new colorschemes

### ISSUE THREAD

**Issue by MaikKlein** [powerline/powerline#1795]
I copied solarized.json to solarizedlight.json `~/.config/powerline/colorschemes/tmux/solarizedlight.json`.

I also added it in `config_files/colorschemes/tmux/solarizedlight.json`
I changed the `config.py`
```
		"tmux": {
			"colorscheme": "solarizedlight",
			"theme": "default"
		},
```
But then I get this error
```
➜  ~ powerline-config tmux setup
Traceback (most recent call last):
  File "/home/maik/.local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/home/maik/.local/lib/python2.7/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/home/maik/.local/lib/python2.7/site-packages/powerline/bindings/config.py", line 211, in tmux_setup
    init_tmux_environment(pl, args, set_tmux_environment=ste)
  File "/home/maik/.local/lib/python2.7/site-packages/powerline/bindings/config.py", line 124, in init_tmux_environment
    highlight = get_highlighting(highlight_group)
  File "/home/maik/.local/lib/python2.7/site-packages/powerline/bindings/config.py", line 110, in get_highlighting
    return colorscheme.get_highlighting([group], None)
  File "/home/maik/.local/lib/python2.7/site-packages/powerline/colorscheme.py", line 105, in get_highlighting
    raise KeyError('Highlighting groups not found in colorscheme: ' + ', '.join(groups))
KeyError: u'Highlighting groups not found in colorscheme: background
```

**Comment by ZyX-I** [comment]
Colorschemes for tmux/etc normally consist of up to *three* files: `colorschemes/{name}.json`, `colorschemes/{ext}/__main__.json` and `colorschemes/{ext}/{name}.json`. While second is applied to all existing colorschemes you copied only third without the second. Of course, this did not work: most groups are in the first, not in the third.

**Comment by ZyX-I** [comment]
Also error is pretty descriptive: “Highlight groups not found”. And better check your config with `powerline-lint`.
