### ISSUE TITLE
Traceback when hitting Ctrl+c quickly on F26/Python 3.6

### ISSUE THREAD

**Issue by xenithorb** [powerline/powerline#1801]
Possibly related to: https://github.com/powerline/powerline/issues/1800

### Setup info: 

OS: Fedora 26 
Python: Python 3.6
Powerline: From official repository
```
powerline-fonts-2.6-1.fc26.noarch
powerline-2.6-1.fc26.x86_64
tmux-powerline-2.6-1.fc26.noarch
powerline-docs-2.6-1.fc26.noarch
vim-powerline-2.6-1.fc26.noarch
```

Initialized with the following in `~/.bashrc`:

```
powerline-daemon -q
export POWERLINE_BASH_CONTINUATION=1
export POWERLINE_BASH_SELECT=1
. /usr/share/powerline/bash/powerline.sh
```

### Problem:

When hitting Ctrl+c on the commandline quickly, the following happens:

```
 xenith  ~  ^C
^C
Traceback (most recent call last):
  File "/usr/bin/powerline", line 19, in <module>
    from powerline.lib.encoding import get_preferred_output_encoding
  File "/usr/lib/python3.6/site-packages/powerline/__init__.py", line 11, in <module>
    from powerline.lib.config import ConfigLoader
  File "/usr/lib/python3.6/site-packages/powerline/lib/config.py", line 11, in <module>
    from powerline.lib.threaded import MultiRunnedThread
  File "/usr/lib/python3.6/site-packages/powerline/lib/threaded.py", line 8, in <module>
    from powerline.segments import Segment
  File "/usr/lib/python3.6/site-packages/powerline/segments/__init__.py", line 6, in <module>
    from pkgutil import extend_path
  File "/usr/lib64/python3.6/pkgutil.py", line 6, in <module>
    import importlib.util
  File "/usr/lib64/python3.6/importlib/util.py", line 13, in <module>
    from contextlib import contextmanager
  File "/usr/lib64/python3.6/contextlib.py", line 228, in <module>
    class suppress(AbstractContextManager):
  File "/usr/lib64/python3.6/abc.py", line 147, in __new__
    cls._abc_negative_cache = WeakSet()
  File "/usr/lib64/python3.6/_weakrefset.py", line 37, in __init__
    self.data = set()
KeyboardInterrupt
^C
^C
Traceback (most recent call last):
  File "/usr/bin/powerline", line 19, in <module>
    from powerline.lib.encoding import get_preferred_output_encoding
  File "/usr/lib/python3.6/site-packages/powerline/__init__.py", line 11, in <module>
    from powerline.lib.config import ConfigLoader
  File "/usr/lib/python3.6/site-packages/powerline/lib/config.py", line 11, in <module>
    from powerline.lib.threaded import MultiRunnedThread
  File "/usr/lib/python3.6/site-packages/powerline/lib/threaded.py", line 8, in <module>
    from powerline.segments import Segment
  File "/usr/lib/python3.6/site-packages/powerline/segments/__init__.py", line 6, in <module>
    from pkgutil import extend_path
  File "/usr/lib64/python3.6/pkgutil.py", line 6, in <module>
    import importlib.util
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
KeyboardInterrupt
 xenith  ~  130  ^C
^C
Traceback (most recent call last):
  File "/usr/bin/powerline", line 19, in <module>
    from powerline.lib.encoding import get_preferred_output_encoding
  File "/usr/lib/python3.6/site-packages/powerline/__init__.py", line 6, in <module>
    import logging
  File "/usr/lib64/python3.6/logging/__init__.py", line 28, in <module>
    from string import Template
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap_external>", line 450, in _validate_bytecode_header
KeyboardInterrupt
 xenith  ~  130  ^C
^C
Traceback (most recent call last):
  File "/usr/bin/powerline", line 19, in <module>
    from powerline.lib.encoding import get_preferred_output_encoding
  File "/usr/lib/python3.6/site-packages/powerline/__init__.py", line 6, in <module>
    import logging
  File "/usr/lib64/python3.6/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections
  File "/usr/lib64/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib64/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/lib64/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/usr/lib64/python3.6/re.py", line 123, in <module>
    import sre_compile
  File "/usr/lib64/python3.6/sre_compile.py", line 14, in <module>
    import sre_parse
  File "/usr/lib64/python3.6/sre_parse.py", line 74, in <module>
    class Pattern:
KeyboardInterrupt
^C
Traceback (most recent call last):
  File "/usr/bin/powerline", line 19, in <module>
    from powerline.lib.encoding import get_preferred_output_encoding
  File "/usr/lib/python3.6/site-packages/powerline/__init__.py", line 11, in <module>
    from powerline.lib.config import ConfigLoader
  File "/usr/lib/python3.6/site-packages/powerline/lib/config.py", line 12, in <module>
    from powerline.lib.watcher import create_file_watcher
  File "/usr/lib/python3.6/site-packages/powerline/lib/watcher/__init__.py", line 7, in <module>
    from powerline.lib.watcher.inotify import INotifyFileWatcher
  File "/usr/lib/python3.6/site-packages/powerline/lib/watcher/inotify.py", line 10, in <module>
    from powerline.lib.inotify import INotify
  File "/usr/lib/python3.6/site-packages/powerline/lib/inotify.py", line 10, in <module>
    from ctypes.util import find_library
  File "/usr/lib64/python3.6/ctypes/util.py", line 2, in <module>
    import shutil
  File "/usr/lib64/python3.6/shutil.py", line 983, in <module>
    _ntuple_diskusage = collections.namedtuple('usage', 'total used free')
  File "/usr/lib64/python3.6/collections/__init__.py", line 431, in namedtuple
    exec(class_definition, namespace)
  File "<string>", line 1, in <module>
KeyboardInterrupt
```

Confirmed this with another user as well

**Comment by xenithorb** [comment]
I assume this is due to the lag, hitting `Ctrl+C` mid generation causes an error like this, so this may not even warrant its own bug next to #1800

**Comment by ZyX-I** [comment]
You are using a daemon, but in place of the compiled powerline executable you use the slowest “python client” option. There are three: socat-based sh script, Python-based python script and a compiled C script. When installing with pip these are chosen automatically: should the compiler be found by distutils C variant will be used, should `socat` be found shell variant will be used, Python as the absolute fallback. Given that you installed from the official repository you need to ask whoever packaged your powerline version.

Same answer in #1800.

**Comment by ZyX-I** [comment]
And tracebacks from the Python client, as well as tracebacks from `powerline-render` script (in case you are not using the daemon) are not bugs.

**Comment by xenithorb** [comment]
Why did it work fine on F25? It's the same package version, what changed around it was Python 3.6 

If using the python script is the cause, then you haven't really adequately explained why it got slower with python 3.6

See here: https://apps.fedoraproject.org/packages/powerline All versions are the same, so the likelihood of what those packages put on the system being same, regardless of OS version is very high. What would matter in that case is what changed (got upgraded) as a dependency. 

Why didn't you comment on the differing behavior of the GIF? Does that seem normal to you?

**Comment by ZyX-I** [comment]
I do not know what they changed when packaged for F26 so that it does not work. You may check which client is used by using `file "$(which powerline)"`.

**Comment by xenithorb** [comment]
### F25:

file $(which powerline)
/usr/bin/powerline: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=04e4042f5650ff2b23f858862231a59472aeaddd, stripped

### F26:
file $(which powerline)
/usr/bin/powerline: Python script, ASCII text executable

So at least now we know. I'll handle the rest downstream.

Does the python version not use the daemon? Or is it just that the python version is as slow as the C version without the daemon? Coincidence?

**Comment by ZyX-I** [comment]
Based on logs it looks like what was changed is the compiler: whatever they used before did not fail with

```
client/powerline.c: In function ‘main’:
client/powerline.c:125:36: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
  snprintf(num_args, NUM_ARGS_SIZE, "%x", argc - 1);
                                    ^~~~
In file included from /usr/include/stdio.h:939:0,
                 from client/powerline.c:4:
/usr/include/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 2 and 9 bytes into a destination of size 8
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/ccnYAn7R.o: In function `main':
/builddir/build/BUILD/powerline-2.6/client/powerline.c:114: undefined reference to `true_sun_len'
```

. The first warning, while being true, is easy to fix, is not really a bug (number of arguments will not ever have the INT_MAX order of magnitude to care about) and is not failing compilation as far as I see. But why compiler does not see `true_sun_len` which is an inline function, defined unconditionally, I do not know.

**Comment by xenithorb** [comment]
Well, F26 upgraded Glibc and `gcc`:

```
gcc (GCC) 7.1.1 20170622 (Red Hat 7.1.1-3)
```
glibc:
```
glibc-2.25-6.fc26.x86_64
```

Maybe that's a clue?

**Comment by ZyX-I** [comment]
Glibc should be irrelevant. That version of GCC is masked (not marked unstable as everything above 4.9.4, masked) on Gentoo, not sure why, but would not be surprised that they masked it because it fails to build system.

**Comment by ZyX-I** [comment]
I.e. I do not have that GCC locally and not going to until it is unmasked.

**Comment by ZyX-I** [comment]
Though no, theoretically that may be a bug in glibc macros should they implement `connect` as a macros. I currently don’t have much ideas about what they may write there to get a bug, no ideas what they may write to get a bug and not screw up many other socket API users.

**Comment by xenithorb** [comment]
Yes I can confirm that building it myself in a reproducible environment that the following occurs:

```
client/powerline.c: In function ‘main’:
client/powerline.c:125:36: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character
  snprintf(num_args, NUM_ARGS_SIZE, "%x", argc - 1);
                                    ^~~~
In file included from /usr/include/stdio.h:939:0,
                 from client/powerline.c:4:
/usr/include/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 2 and 9 bytes into a destination of si
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/ccKwNdgL.o: In function `main':
/builddir/build/BUILD/powerline-2.6/client/powerline.c:114: undefined reference to `true_sun_len'
collect2: error: ld returned 1 exit status
ERROR:root:Command '['cc', '-O2', '-g', '-pipe', '-Wall', '-Werror=format-security', '-Wp,-D_FORTIFY_SOURCE=2', '-fexcep
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    compile_client()
  File "setup.py", line 35, in compile_client
    subprocess.check_call(compiler + shlex.split(cflags) + ['client/powerline.c', '-o', 'scripts/powerline'])
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cc', '-O2', '-g', '-pipe', '-Wall', '-Werror=format-security', '-Wp,-D_FORTIFY
Compiling C version of powerline-client failed
Using powerline.py script instead of C version
```

There are slight differences between the two SPEC files in each fedora version -- namely the f26 SPEC, has this message:

```
+# As we only have python files do not create a debuginfo package
+%global debug_package %{nil}
```
And they also switch the build to be a `noarch` package. It seems they recognized that they were now getting python-only output, but didn't seem to realize that it was because it was failing to build properly, or they did and decided to ship it like this.

**Comment by xenithorb** [comment]
https://github.com/powerline/powerline/pull/1803 Fixes this issue
