### ISSUE TITLE
pip install error: keyword argument repeated

### ISSUE THREAD

**Issue by holms** [powerline/powerline#1881]
Some strange issue in here:

```
roman@debian:~$ sudo pip3 install powerline
Collecting powerline
  Downloading powerline-0.2.4.zip (79kB)
    100% |████████████████████████████████| 81kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7akfdw_j/powerline/setup.py", line 27
        zip_safe = False,
        ^
    SyntaxError: keyword argument repeated
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7akfdw_j/powerline/
```

This is also a case for python2.7:

```
roman@debian:~$ sudo pip install powerline
Collecting powerline
  Using cached powerline-0.2.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-KOKltN/powerline/setup.py", line 27
        zip_safe = False,
    SyntaxError: keyword argument repeated
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KOKltN/powerline/
```

My env:

```
roman@debian:~$ python --version
Python 2.7.13
roman@debian:~$ python3 --version
Python 3.5.3
roman@debian:~$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
roman@debian:~$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
roman@debian:~$ uname -a
Linux debian 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
```

**Comment by holms** [comment]
Alright excuse me it's powerline-status in pip

**Comment by xiaohk** [comment]
same here
