### ISSUE TITLE
error press CTRL + C

### ISSUE THREAD

**Issue by azhari33** [powerline/powerline#1894]
Traceback (most recent call last):
File "/usr/local/bin/powerline-shell", line 11, in
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/powerline_shell/init.py", line 191, in main
segment.add_to_powerline()
File "/usr/local/lib/python2.7/dist-packages/powerline_shell/segments/hg.py", line 67, in add_to_powerline
self.join()
File "/usr/lib/python2.7/threading.py", line 940, in join
self.__block.wait()
File "/usr/lib/python2.7/threading.py", line 340, in wait
waiter.acquire()
KeyboardInterrupt
^C
Traceback (most recent call last):
File "/usr/local/bin/powerline-shell", line 11, in
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/powerline_shell/init.py", line 191, in main
segment.add_to_powerline()
File "/usr/local/lib/python2.7/dist-packages/powerline_shell/segments/git.py", line 93, in add_to_powerline
self.join()
File "/usr/lib/python2.7/threading.py", line 940, in join
self.__block.wait()
File "/usr/lib/python2.7/threading.py", line 340, in wait
waiter.acquire()
KeyboardInterrupt

**Comment by ZyX-I** [comment]
Tracebacks in case of interrupting prompt evaluation is not something I am going to fix ever. If speed of prompt evaluation is not fine, use daemon. With C or shell client it is not going to yield any tracebacks as you could interrupt client this way and not a daemon.
