### ISSUE TITLE
Python errors with "status_colors": true" in bash

### ISSUE THREAD

**Issue by thierrybo** [powerline/powerline#1904]
Following you comment [here](https://github.com/powerline/powerline/issues/1108#issuecomment-385698363), I created a new issue.

I removed Debian powerline package (2.5) ans install 2.6 as root from github. Here is my .bashrc :
```
if [ -f `which powerline-daemon` ]; then
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
#. /usr/share/powerline/bindings/bash/powerline.sh
  .  /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh  
fi
```
and my theme.json:
```
{
	"segments": {
		"left": [
			{
				"function": "powerline.segments.common.net.hostname",
				"priority": 10
			},
			{
				"function": "powerline.segments.common.env.user",
				"priority": 30
			},
			{
				"function": "powerline.segments.common.env.virtualenv",
				"priority": 50
			},
			{
				"function": "powerline.segments.shell.cwd",
				"priority": 10
			},
			{
				"function": "powerline.segments.shell.jobnum",
				"priority": 20
			},
			{
				"function": "powerline.segments.shell.last_status",
				"priority": 10
			},
			{
				"function": "powerline.segments.common.vcs.branch",
				"priority": 40,
                "args": {
                    "ignore_statuses": "U",
                    "status_colors": true
                }
			},
			{
				"function": "powerline.segments.common.vcs.stash",
				"priority": 50
			}
		]
	}
}
```
On some git folders, but not all, I get this error :
```
2018-05-02 13:25:56,534:ERROR:shell:branch:Exception while computing segment: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/powerline/segment.py", line 173, in process_segment
    contents = segment['contents_func'](pl, segment_info)
  File "/usr/local/lib/python2.7/dist-packages/powerline/segment.py", line 412, in <lambda>
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, segment_info=segment_info, **args)
  File "/usr/local/lib/python2.7/dist-packages/powerline/segments/common/vcs.py", line 33, in __call__
    if status in ignore_statuses:
TypeError: coercing to Unicode: need string or buffer, NoneType found

```
![powerline_stats_colors_true 01-05-2018 16-33](https://user-images.githubusercontent.com/3847603/39521442-cd783480-4e0e-11e8-8e5b-5efab5b8fa04.gif)

**Comment by ZyX-I** [comment]
Ah, got it. With the configuration posted I see the error: `ignore_statuses` must be a list, *not* string. This is explicitly stated in [documentation](http://powerline.readthedocs.io/en/master/configuration/segments/common.html#powerline.segments.common.vcs.branch), there is an example (and also type, in master that is bool, but in [develop](http://powerline.readthedocs.io/en/develop/configuration/segments/common.html#powerline.segments.common.vcs.branch) it was fixed to be a list).

**Comment by thierrybo** [comment]
thanks
