### ISSUE TITLE
Failed pip install

### ISSUE THREAD

**Issue by Fuzion24** [powerline/powerline#1910]
```
➜  ~ pip install powerline
Collecting powerline
  Using cached https://files.pythonhosted.org/packages/e2/a3/e6103f3225318e4761a87519b00b7d3b4dfc7f55c5ab1f4c7a7c5f003b10/powerline-0.2.4.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8t/9c_383h10sl73bf4z7rfjnkh0000gn/T/pip-install-OaTXSU/powerline/setup.py", line 27
        zip_safe = False,
    SyntaxError: keyword argument repeated
```

**Comment by Fuzion24** [comment]
powerline name collision 
`pip install powerline-status` not `pip install powerline`
