### ISSUE TITLE
Powerline throws BrokenPipeError with lemonbar when i3/Xorg exits

### ISSUE THREAD

**Issue by kmoschcau** [powerline/powerline#1920]
Hi, I just recently started using lemonbar with powerline. Most of the stuff works fine, except this one thing that keeps nagging me.
I have lemonbar with powerline running in i3 and whenever I exit i3 and the x-server with `i3-msg exit`, it starts spamming the linux terminal with BrokenPipeErrors. Roughly one every second.
```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/site-packages/powerline/bindings/lemonbar/powerline-lemonbar.py", line 40, in render
    process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/site-packages/powerline/bindings/lemonbar/powerline-lemonbar.py", line 40, in render
    process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/site-packages/powerline/bindings/lemonbar/powerline-lemonbar.py", line 40, in render
    process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

My setup for powerline and lemonbar in my i3 config looks like this:
```conf
# Use lemonbar with powerline instead of i3bar and i3status
exec "python /home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/site-packages/powerline/bindings/lemonbar/powerline-lemonbar.py --i3 --bar-command lemonbar -- -f -windows-dinapowerline-medium-r-*-*-13-*-*-*-*-*-*-*"
```
The same thing also happens, when I run this exec command manually and then send a SIGINT. It only stops when I send a second SIGINT.

**Comment by kmoschcau** [comment]
I just realized, that the `--i3` flag is not needed for lemonbar, so I removed it. But the behavior is still the same.

**Comment by kmoschcau** [comment]
After some fiddling around with different combinations of kill commands sent to either the lemonbar processes or the powerline process itself, I was also able to provoke it to throwing a slightly different error:
```
Exception in thread Thread-109:
Traceback (most recent call last):
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/home/kmoschcau/.pyenv/versions/3.6.5/lib/python3.6/site-packages/powerline/bindings/lemonbar/powerline-lemonbar.py", line 39, in render
    process.stdin.write(powerline.render(mode=modes[0], width=width, matcher_info=output).encode('utf-8') + b'\n')
BrokenPipeError: [Errno 32] Broken pipe
```
What might also be of interest is, that I use two displays. So powerline spawns two lemonbar processes. I can kill each one and they continue as zombie processes. As well as each of them killed causes the powerline process to throw errors.

**Comment by PH111P** [comment]
The problem lies in the current implementation of the  `render` method in [powerline-lemonbar.py](https://github.com/powerline/powerline/blob/develop/powerline/bindings/lemonbar/powerline-lemonbar.py#L32): Despite the `lemonbar` process having died (thus the `BrokenPipeError`), a new Timer is created which will call `render` again after `--interval` seconds (which defaults to 1 second), producing another `BrokenPipeError`.

**Comment by kmoschcau** [comment]
@PH111P Concerning the `--i3` flag: I installed `i3ipc` after first reading the documentation when I installed and set up lemonbar with powerline and the workspaces were working then. I removed the flag and the workspaces still work.
I mean you are supposed to do it like this, right?
```json
{
  "function": "powerline.listers.i3wm.workspace_lister",
  "segments": [
    {
      "function": "powerline.segments.i3wm.workspace"
    }
  ],
  "type":     "segment_list"
}
```
Because the `workspaces` segment gave me a deprecated warning in `powerline-lint`.

**Comment by s-ol** [comment]
@kmoschcau: An i3-ipc library is needed in two different places:
- in the segments that display i3-state (= the workspace segment)
- *optionally* in the lemonbar binding (enabled with `--i3`)

In the binding the library is used to force re-renders whenever the workspace changes so that segments like the workspace segment react more quickly. without `--i3` it only renders on a fixed periodic schedule (0.5s default i think) which can seem quite unresponsive.

**Comment by kmoschcau** [comment]
@s-ol Now that you mention it, I started two bars one with and one without the flag and the one without did indeed seem slower to react to workspace switching.
