### ISSUE TITLE
Installation error on iTerm2 with ohmyzsh

### ISSUE THREAD

**Issue by garyfanhku** [powerline/powerline#1928]
`Traceback (most recent call last):
  File "/Users/****/anaconda/bin/powerline-config", line 6, in <module>
    from powerline.commands.config import get_argparser
  File "/Users/****/anaconda/lib/python2.7/site-packages/powerline/commands/config.py", line 6, in <module>
    import powerline.bindings.config as config
  File "/Users/*****/anaconda/lib/python2.7/site-packages/powerline/bindings/config.py", line 19, in <module>
    from powerline.commands.main import finish_args
  File "/Users/****/anaconda/lib/python2.7/site-packages/powerline/commands/main.py", line 18, in <module>
    encoding = get_preferred_arguments_encoding()
  File "/Users/****/anaconda/lib/python2.7/site-packages/powerline/lib/encoding.py", line 89, in get_preferred_arguments_encoding
    locale.getdefaultlocale()[1]
  File "/Users/****/anaconda/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/****/anaconda/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8`

**Comment by garyfanhku** [comment]
`export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8`
These 2 lines added to the zshrc solved my issue.

**Comment by royaso** [comment]
> `export LC_ALL=en_US.UTF-8 export LANG=en_US.UTF-8`
> These 2 lines added to the zshrc solved my issue.

It took me hours to finally work this out! thanks!
