### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by zuxfoucault** [powerline/powerline#1930]
When macvim started, I encountered the following error mesg:
```
2018-07-12 15:56:26,292:ERROR:vim:virtcol_current:Exception while computing segment: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segment.py", line 173, in process_segment
    contents = segment['contents_func'](pl, segment_info)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segment.py", line 412, in <lambda>
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, segment_info=segment_info, **args)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segments/vim/__init__.py", line 83, in ret
    r = func(**kwargs)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segments/vim/__init__.py", line 470, in virtcol_current
    textwidth = int(getbufvar('%', '&textwidth'))
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/bindings/vim/__init__.py", line 264, in getbufvar
    return _vim_to_python(_getbufvar(*args))
TypeError: 'NoneType' object is not callable
```

**Comment by docwhite** [comment]
Happening to me as well with normal vim on Mac too.

**Comment by ronindesign** [comment]
Pretty sure this is happening to me, hard to tell for certain, as I only see the last line of the error:
`TypeError: 'NoneType' object is not callable`

I just did fresh install on Mac OS X, homebrew, macvim (binary), python 3.7:

**Python**

```
➜  ~ python -V
Python 3.7.0
➜  ~ which python
/usr/local/opt/python/libexec/bin/python
➜  ~ ls -al `!!`
➜  ~ ls -al `which python`
lrwxr-xr-x  1 static  admin  60 Jun 26 23:06 /usr/local/opt/python/libexec/bin/python -> ../../Frameworks/Python.framework/Versions/3.7/bin/python3.7
```

**MacVim**
```
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jul 16 2018 10:00:33)
macOS version
Included patches: 1-72
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_netterm     +tag_binary
+arabic            +file_in_path      +mouse_sgr         +tag_old_static
+autocmd           +find_in_path      -mouse_sysmouse    -tag_any_white
-autoservername    +float             +mouse_urxvt       +tcl
+balloon_eval      +folding           +mouse_xterm       +termguicolors
+balloon_eval_term -footer            +multi_byte        +terminal
+browse            +fork()            +multi_lang        +terminfo
++builtin_terms    +fullscreen        -mzscheme          +termresponse
+byte_offset       -gettext           +netbeans_intg     +textobjects
+channel           -hangul_input      +num64             +timers
+cindent           +iconv             +odbeditor         +title
+clientserver      +insert_expand     +packages          +toolbar
+clipboard         +job               +path_extra        +transparency
+cmdline_compl     +jumplist          +perl              +user_commands
+cmdline_hist      +keymap            +persistent_undo   +vertsplit
+cmdline_info      +lambda            +postscript        +virtualedit
+comments          +langmap           +printer           +visual
+conceal           +libcall           +profile           +visualextra
+cryptv            +linebreak         -python            +viminfo
+cscope            +lispindent        +python3           +vreplace
+cursorbind        +listcmds          +quickfix          +wildignore
+cursorshape       +localmap          +reltime           +wildmenu
+dialog_con_gui    -lua               +rightleft         +windows
+diff              +menu              +ruby              +writebackup
+digraphs          +mksession         +scrollbind        -X11
+dnd               +modify_fname      +signs             -xfontset
-ebcdic            +mouse             +smartindent       +xim
+emacs_tags        +mouseshape        +startuptime       -xpm
+eval              +mouse_dec         +statusline        -xsmp
+ex_extra          -mouse_gpm         -sun_workshop      -xterm_clipboard
+extra_search      -mouse_jsbterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby
```

**Comment by zuxfoucault** [comment]
see logs by `/usr/local/bin/mvim -g -f 2> macvim.log`

**Comment by jooray** [comment]
Same here, looks very similar to the output above. Plus the log:

```
2018-08-05 17:07:13,198:ERROR:vim:virtcol_current:Exception while computing segment: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segment.py", line 173, in process_segment
    contents = segment['contents_func'](pl, segment_info)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segment.py", line 412, in <lambda>
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, segment_info=segment_info, **args)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segments/vim/__init__.py", line 83, in ret
    r = func(**kwargs)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segments/vim/__init__.py", line 470, in virtcol_current
    textwidth = int(getbufvar('%', '&textwidth'))
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/bindings/vim/__init__.py", line 264, in getbufvar
    return _vim_to_python(_getbufvar(*args))
TypeError: 'NoneType' object is not callable
```

**Comment by nehasoni3** [comment]
> When macvim started, I encountered the following error mesg:
> 
> ```
> 2018-07-12 15:56:26,292:ERROR:vim:virtcol_current:Exception while computing segment: 'NoneType' object is not callable
> Traceback (most recent call last):
>   File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segment.py", line 173, in process_segment
>     contents = segment['contents_func'](pl, segment_info)
>   File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segment.py", line 412, in <lambda>
>     contents_func = lambda pl, segment_info: _contents_func(pl=pl, segment_info=segment_info, **args)
>   File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segments/vim/__init__.py", line 83, in ret
>     r = func(**kwargs)
>   File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/segments/vim/__init__.py", line 470, in virtcol_current
>     textwidth = int(getbufvar('%', '&textwidth'))
>   File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powerline/bindings/vim/__init__.py", line 264, in getbufvar
>     return _vim_to_python(_getbufvar(*args))
> TypeError: 'NoneType' object is not callable
> ```
I am getting the same error.
