### ISSUE TITLE
Have to install in each virtualenv

### ISSUE THREAD

**Issue by diogobaeder** [powerline/powerline#1937]
Hi guys,

I upgraded a bunch of stuff on my Arch Linux box today - which included Python 3.7 -, and started having an issue with powerline: all of a sudden it just won't run anymore inside virtualenvs unless I install it explicitly in those envs. Previously it ran just fine - it was probably kicking in before the virtualenv got activated, hence it used the system environment (with powerline installed) -, but now it seems to be kicking in after the virtualenv gets activated (and I didn't change anything in my .bashrc ).

This is the error I get:
```
Traceback (most recent call last):
  File "/usr/bin/powerline", line 19, in <module>
    from powerline.lib.encoding import get_preferred_output_encoding
ModuleNotFoundError: No module named 'powerline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/powerline", line 22, in <module>
    from powerline.lib.encoding import get_preferred_output_encoding
ModuleNotFoundError: No module named 'powerline'
```

Any ideas?

**Comment by diogobaeder** [comment]
Interesting, explicitly adding the PYTHONPATH to my bashrc made it work fine:

```
export PYTHONPATH=/usr/lib/python3.7/site-packages
```

Which makes sense, but I wonder why it didn't work before...

Anyway, feel free to close the ticket, but I wonder if there's a more elegant way to solve this.

**Comment by diogobaeder** [comment]
Just as a reference, this is the relevant part in my bashrc:

```bash
export SITE_PACKAGES=`python -c 'import site; print(site.getsitepackages()[0])'`
export PYTHONPATH=$SITE_PACKAGES

if [ -f $SITE_PACKAGES/powerline/bindings/bash/powerline.sh ]; then
	powerline-daemon -q
	POWERLINE_BASH_CONTINUATION=1
	POWERLINE_BASH_SELECT=1
	. $SITE_PACKAGES/powerline/bindings/bash/powerline.sh
fi
```
I left `SITE_PACKAGES` and `PYTHONPATH` there just in case I need to comment out `PYTHONPATH`.

**Comment by diogobaeder** [comment]
Actually, explicitly setting the `PYTHONPATH` is not a good idea either, because it breaks with the virtualenvs, in that they start getting access to the system packages as well.

Back to square 1. :-(

**Comment by ZyX-I** [comment]
You for some reason have Python client, it is the worst variant out there: not only susceptible to the issue you are seeing, but also has worst performance. Daemon is not affected by the virtual environment (except the one you run it in if any), but Python client is. Socat-based and C clients are not, but those are selected at installation time (at build time if you are using system package manager) and need either `socat` installed or C compiler.

This may be a consequnece of #1913 and fix missing from the release.

**Comment by gdiscry** [comment]
I have the same issue (I also use Arch Linux).

While you are right that the compilation of the C client probably failed and fell back to the Python client, there is still an issue when installing the Python client. The Python client keeps the relative shebang `#!/usr/bin/env python` (and thus uses the python from the virtualenv instead of the system python). In all the other scripts, the shebang is replaced by the absolute shebang `#!/usr/bin/python` or `#!/usr/bin/python2`.

When `scripts/powerline` is the python client, it should not be added to the `data_files` argument. That way distutils will replace the relative shebang with an absolute one.

**Comment by martinezhermes** [comment]
I wonder if my case is related. I have multiple virtualenvs, once I activate a virtualenv and I launch the inner ipython it produces an error ModuleNotFound: powerline and I have to install powerline for that environment. Is there a way for ipython from venvs to read from the local python library of the system?

**Comment by BlitzKraft** [comment]
@martinezhermes : I use powerline with multiple virtualenvs, with a default install and I don't see this issue. Also, pip modules installed system-wide are also available within any virtualenv. Is it possible this is an issue with virtualenv/pip?

**Comment by martinezhermes** [comment]
@BlitzKraft, Do you have ipython installed outside the environments? I keep my system's python3 with powerline and virtualenv and then install whatever I need in a minimal environment for the specific task.

**Comment by martinezhermes** [comment]
> pip modules installed system-wide are also available within any virtualenv.
This should not be the case, a virtual environment should not be allowed to system-wide libraries, that would defeat their purpose.

**Comment by BlitzKraft** [comment]
I was wrong. I confused "being available in the $PATH" with being available with python import. Sorry for the misunderstanding.

**Comment by fogine** [comment]
When you install `powerline` into virtualenv you need to provide absolute paths to executables... to have it working even when you have activated virtual environment without powerline dependency installed... 
`powerline.zsh` which is sourced in zshrc calls `powerline` and expect it to be found in `$PATH`... So the solution is to set `$POWERLINE_COOMAND` to the absolute powerline path, before sourcing the file:

```bash
if [ -f ~/.pyenv/versions/powerline/lib/python3.6/site-packages/powerline/bindings/zsh/powerline.zsh ]; then
  ~/.pyenv/versions/powerline/bin/powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  #set powerline command since we installed powerline in virtualenv
  #this fixes broken shell powerline when we do:
  #> pyenv activate some-project-without-powerline-dependency-installed
  export POWERLINE_COMMAND=~/.pyenv/versions/powerline/bin/powerline
  . ~/.pyenv/versions/powerline/lib/python3.6/site-packages/powerline/bindings/zsh/powerline.zsh
fi

```
