### ISSUE TITLE
locale issues on macos "ValueError: unknown locale: UTF-8"

### ISSUE THREAD

**Issue by Helmi** [powerline/powerline#1968]
I'm facing an error on macOS after running fish with powerline for a while without issues. I'm pretty sure the problem is somewhere on my side but I can't seem to find it. After googling around I noticed others see this error with locales not being set correctly on macOS and indeed I had incompletely set env variables too but even setting them doesn't seem to help.

Here's the error I get when opening a new iTerm tab (aka shell session)

```
Last login: Wed Nov 28 11:25:31 on ttys003
Traceback (most recent call last):
  File "/usr/local/bin/powerline-daemon", line 24, in <module>
    from powerline.commands.main import finish_args, write_output
  File "/usr/local/lib/python2.7/site-packages/powerline/commands/main.py", line 18, in <module>
    encoding = get_preferred_arguments_encoding()
  File "/usr/local/lib/python2.7/site-packages/powerline/lib/encoding.py", line 89, in get_preferred_arguments_encoding
    locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Traceback (most recent call last):
  File "/usr/local/bin/powerline-config", line 6, in <module>
    from powerline.commands.config import get_argparser
  File "/usr/local/lib/python2.7/site-packages/powerline/commands/config.py", line 6, in <module>
    import powerline.bindings.config as config
  File "/usr/local/lib/python2.7/site-packages/powerline/bindings/config.py", line 19, in <module>
    from powerline.commands.main import finish_args
  File "/usr/local/lib/python2.7/site-packages/powerline/commands/main.py", line 18, in <module>
    encoding = get_preferred_arguments_encoding()
  File "/usr/local/lib/python2.7/site-packages/powerline/lib/encoding.py", line 89, in get_preferred_arguments_encoding
    locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Traceback (most recent call last):
  File "/usr/local/bin/powerline-config", line 6, in <module>
    from powerline.commands.config import get_argparser
  File "/usr/local/lib/python2.7/site-packages/powerline/commands/config.py", line 6, in <module>
    import powerline.bindings.config as config
  File "/usr/local/lib/python2.7/site-packages/powerline/bindings/config.py", line 19, in <module>
    from powerline.commands.main import finish_args
  File "/usr/local/lib/python2.7/site-packages/powerline/commands/main.py", line 18, in <module>
    encoding = get_preferred_arguments_encoding()
  File "/usr/local/lib/python2.7/site-packages/powerline/lib/encoding.py", line 89, in get_preferred_arguments_encoding
    locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Welcome to fish, the friendly interactive shell
``` 

I'm using brew installed python 2.7.15 as system default (linked) and could use 3.7 as well to install powerline but the result is the same

I already set this in config.fish

```
set -x LANG de_DE.UTF-8
set -x LC_ALL de_DE.UTF-8
set -x LC_CTYPE de_DE.UTF-8
``` 

and locales seem to look good:
```
~ ❯❯❯ locale                                                                                                                                                                                 11:26:33
LANG="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_ALL="de_DE.UTF-8"
``` 

already tried en_US.UTF-8 too for the sake of testing but didn't change anything.

any idea what's going on there? I don't see any similar problem with any other python tool.

macOS is latest (10.14.1) but as I said it already worked in the same environment and I can't say I changed anything to my knowledge.

**Comment by Helmi** [comment]
my bad - it's been an issue with iTerm2 being outdated. However it happened but the auto update was deactivated and bringing it to the latest version solved the issue.
