### ISSUE TITLE
Error when running `powerline-config tmux setup` macOS Mojave, Fish Shell

### ISSUE THREAD

**Issue by bennypowers** [powerline/powerline#1981]
Here's the output from `powerline-config tmux setup`

```
2019-02-12 08:03:46,549:ERROR:__unknown__:Could not execute command ([Errno 2] No such file or directory): [u'tmux', u'-V']
Traceback (most recent call last):
  File "/Users/bennyp/Library/Python/2.7/lib/python/site-packages/powerline/lib/shell.py", line 34, in run_cmd
    p = Popen(cmd, shell=False, stdout=PIPE, stdin=PIPE)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/Users/bennyp/Library/Python/2.7/lib/python/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/Users/bennyp/Library/Python/2.7/lib/python/site-packages/powerline/bindings/config.py", line 184, in tmux_setup
    tmux_version = get_tmux_version(pl)
  File "/Users/bennyp/Library/Python/2.7/lib/python/site-packages/powerline/bindings/tmux/__init__.py", line 77, in get_tmux_version
    _, version_string = version_string.split(' ')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by royaso** [comment]
> Here's the output from `powerline-config tmux setup`
> 
> ```
> 2019-02-12 08:03:46,549:ERROR:__unknown__:Could not execute command ([Errno 2] No such file or directory): [u'tmux', u'-V']
> Traceback (most recent call last):
>   File "/Users/bennyp/Library/Python/2.7/lib/python/site-packages/powerline/lib/shell.py", line 34, in run_cmd
>     p = Popen(cmd, shell=False, stdout=PIPE, stdin=PIPE)
>   File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
>     errread, errwrite)
>   File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Traceback (most recent call last):
>   File "/usr/local/bin/powerline-config", line 22, in <module>
>     args.function(pl, args)
>   File "/Users/bennyp/Library/Python/2.7/lib/python/site-packages/powerline/commands/config.py", line 15, in __call__
>     self.function(*args, **kwargs)
>   File "/Users/bennyp/Library/Python/2.7/lib/python/site-packages/powerline/bindings/config.py", line 184, in tmux_setup
>     tmux_version = get_tmux_version(pl)
>   File "/Users/bennyp/Library/Python/2.7/lib/python/site-packages/powerline/bindings/tmux/__init__.py", line 77, in get_tmux_version
>     _, version_string = version_string.split(' ')
> AttributeError: 'NoneType' object has no attribute 'split'
> ```

me too, But I am using zsh.
wonder if  mojave is the problem

**Comment by BlitzKraft** [comment]
Is tmux installed on the system?
