### ISSUE TITLE
Doesn't work in NeoVim

### ISSUE THREAD

**Issue by RossComputerPerson** [powerline/powerline#1999]
When installed from pacman on Arch Linux, I get this error when opening neovim:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/lib/python3.7/site-packages/powerline/vim.py", line 15, in <module>
    from powerline.bindings.vim import vim_get_func, vim_getvar, get_vim_encoding, python_to_vim
  File "/usr/lib/python3.7/site-packages/powerline/bindings/vim/__init__.py", line 44, in <module>
    vim_encoding = get_vim_encoding()
  File "/usr/lib/python3.7/site-packages/powerline/bindings/vim/__init__.py", line 25, in get_vim_encoding
    return vim.options['encoding'].decode('ascii') or 'ascii'
AttributeError: 'str' object has no attribute 'decode'
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 53, in <module>
  File "<string>", line 40, in powerline_troubleshoot
  File "/usr/lib/python3.7/site-packages/powerline/lint/__init__.py", line 12, in <module>
    from powerline.segments.vim import vim_modes
  File "/usr/lib/python3.7/site-packages/powerline/segments/vim/__init__.py", line 16, in <module>
    from powerline.bindings.vim import (vim_get_func, getbufvar, vim_getbufoption,
  File "/usr/lib/python3.7/site-packages/powerline/bindings/vim/__init__.py", line 44, in <module>
    vim_encoding = get_vim_encoding()
  File "/usr/lib/python3.7/site-packages/powerline/bindings/vim/__init__.py", line 25, in get_vim_encoding
    return vim.options['encoding'].decode('ascii') or 'ascii'
AttributeError: 'str' object has no attribute 'decode'
```
Everything is up to date.

**Comment by PH111P** [comment]
See #1287
