### ISSUE TITLE
IPython Immediately Crashes with Powerline Extension

### ISSUE THREAD

**Issue by naftulikay** [powerline/powerline#2023]
I'm following the guide [here](https://powerline.readthedocs.io/en/latest/usage/other.html?highlight=ipython#ipython-prompt) to integrate IPython and Powerline.

I'm on Linux 5.0.0, Ubuntu 18.04, Python 3.7.4 via pyenv, the latest `powerline-status` from PyPI, and the latest IPython from PyPI (7.8.0).

In `~/.ipython/profile_default/ipython_config.py` I have tried the following:

```python
from powerline.bindings.ipython.since_5 import PowerlinePrompts

c.TerminalInteractiveShell.simple_prompt = False
c.TerminalInteractiveShell.prompts_class = PowerlinePrompts
```

When I attempt to start IPython, I see the following:

```
Traceback (most recent call last):
  File "/home/naftuli/.pyenv/versions/3.7.4/bin/ipython", line 10, in <module>
    sys.exit(start_ipython())
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 498, in mainloop
    self.interact()
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 481, in interact
    code = self.prompt_for_code()
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 410, in prompt_for_code
    **self._extra_prompt_options())
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 738, in prompt
    return run_sync()
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 727, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 709, in run
    return run()
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 683, in run
    return f.result()
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 658, in _run_async2
    result = yield f
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 601, in _run_async
    self._redraw()
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 444, in _redraw
    self.renderer.render(self, self.layout)
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/renderer.py", line 557, in render
    if (self.style.invalidation_hash() != self._last_style_hash or
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/styles/style.py", line 372, in invalidation_hash
    return tuple(s.invalidation_hash() for s in self.styles)
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/styles/style.py", line 372, in <genexpr>
    return tuple(s.invalidation_hash() for s in self.styles)
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/styles/base.py", line 140, in invalidation_hash
    return (self.get_style() or self._dummy).invalidation_hash()
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/styles/base.py", line 140, in invalidation_hash
    return (self.get_style() or self._dummy).invalidation_hash()
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/styles/base.py", line 140, in invalidation_hash
    return (self.get_style() or self._dummy).invalidation_hash()
  File "/home/naftuli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/powerline/renderers/ipython/since_5.py", line 79, in invalidation_hash
    return super(PowerlinePromptStyle, self).invalidation_hash() + 1
TypeError: can only concatenate tuple (not "int") to tuple

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

If I remove the prompts class line, then IPython does start normally. I have also tried the legacy approach mentioned in the documentation.

Is there something I'm doing wrong preventing me from using the IPython integration? I have also restarted the daemon by `powerline-daemon --kill` and starting it over again.

**Comment by PH111P** [comment]
See https://github.com/powerline/powerline/pull/1997 and https://github.com/powerline/powerline/issues/1953.
