### ISSUE TITLE
powerline not displaying in tmux after system restart (osx)

### ISSUE THREAD

**Issue by cflynn07** [powerline/powerline#2068]
Previously I had powerline working in tmux properly, but after a restart the default tmux status bar is displayed.

Previous working setup
<img width="1792" alt="Screen Shot 2020-01-03 at 1 57 51 PM" src="https://user-images.githubusercontent.com/467885/72496600-0aaa3280-3865-11ea-80c7-7fffaa4e8f50.png">

Lack of powerline after restart
<img width="1613" alt="Screen Shot 2020-01-16 at 1 33 19 PM" src="https://user-images.githubusercontent.com/467885/72496554-e77f8300-3864-11ea-8594-88044141f6ad.png">

### tmux version
```
$ tmux -V
tmux 3.0a
```

### output of tmux source
```
tmux source ~/.tmux.conf
2020-01-16 13:36:50,446:ERROR:tmux:powerline:Failed to create renderer: Expecting property name enclosed in double quotes: line 8 column 3 (char 458)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/lib/config.py", line 158, in load
    return deepcopy(self.loaded[path])
KeyError: '/Users/casey/.config/powerline/colorschemes/default.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 859, in update_renderer
    self.create_renderer(**cr_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 669, in create_renderer
    self.colorscheme_config = self.load_colorscheme_config(self.ext_config['colorscheme'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 811, in load_colorscheme_config
    return self._load_hierarhical_config('colorscheme', levels, (1,))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 777, in _load_hierarhical_config
    lvl_config = self.load_config(cfg_path, cfg_type)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 738, in load_config
    return load_config(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 199, in load_config
    mergedicts(ret, config_loader.load(path))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/lib/config.py", line 160, in load
    r = self._load(path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/lib/config.py", line 21, in load_json_config
    return load(config_file_fp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 3 (char 458)
'powerline-config tmux setup' returned 1
```

```
$ powerline-config tmux setup
2020-01-16 13:27:25,533:ERROR:tmux:powerline:Failed to create renderer: Expecting property name enclosed in double quotes: line 8 column 3 (char 458)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/lib/config.py", line 158, in load
    return deepcopy(self.loaded[path])
KeyError: '/Users/casey/.config/powerline/colorschemes/default.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 859, in update_renderer
    self.create_renderer(**cr_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 669, in create_renderer
    self.colorscheme_config = self.load_colorscheme_config(self.ext_config['colorscheme'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 811, in load_colorscheme_config
    return self._load_hierarhical_config('colorscheme', levels, (1,))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 777, in _load_hierarhical_config
    lvl_config = self.load_config(cfg_path, cfg_type)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 738, in load_config
    return load_config(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 199, in load_config
    mergedicts(ret, config_loader.load(path))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/lib/config.py", line 160, in load
    r = self._load(path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/lib/config.py", line 21, in load_json_config
    return load(config_file_fp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 3 (char 458)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/lib/config.py", line 158, in load
    return deepcopy(self.loaded[path])
KeyError: '/Users/casey/.config/powerline/colorschemes/default.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/bindings/config.py", line 214, in tmux_setup
    init_tmux_environment(pl, args, set_tmux_environment=ste)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/bindings/config.py", line 105, in init_tmux_environment
    powerline.update_renderer()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 859, in update_renderer
    self.create_renderer(**cr_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 669, in create_renderer
    self.colorscheme_config = self.load_colorscheme_config(self.ext_config['colorscheme'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 811, in load_colorscheme_config
    return self._load_hierarhical_config('colorscheme', levels, (1,))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 777, in _load_hierarhical_config
    lvl_config = self.load_config(cfg_path, cfg_type)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 738, in load_config
    return load_config(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/__init__.py", line 199, in load_config
    mergedicts(ret, config_loader.load(path))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/lib/config.py", line 160, in load
    r = self._load(path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/lib/config.py", line 21, in load_json_config
    return load(config_file_fp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 3 (char 458)
```

### .tmux.conf 
```
# https://github.com/samoshkin/tmux-config/blob/master/tmux/tmux.conf
# ==========================
# ===  General settings  ===
# ==========================

run-shell "powerline-daemon -q"
source "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/powerline/bindings/tmux/powerline.conf"

# General Appearance

# Pane colors
# set inactive/active window styles
set -g window-style 'fg=colour247, bg=#17202A'
set -g window-active-style 'fg=colour250, bg=#151515'
 
# pane border
set -g pane-border-style 'fg=#5D6D7E, bg=#17202A'
set -g pane-active-border-style 'fg=#1B4F72, bg=#151515'

set -g message-style bg='#44475a',fg='#8be9fd'
#-------------------------------------------------------#

setw -g status-interval 2 # how often the status line is redrawn
set -g buffer-limit 20
set -g display-time 1500
set -g history-limit 20000
set -g remain-on-exit off
set -g renumber-windows on
set -g repeat-time 300
set -sg escape-time 0
setw -g aggressive-resize on
setw -g allow-rename off
setw -g automatic-rename off

# Change prefix key to C-a, easier to type, same to "screen"
unbind C-b
set -g prefix C-a

# Set parent terminal title to reflect current window in tmux session 
set -g set-titles on
set -g set-titles-string "#I:#W"

# Start index of window/pane with 1, because we're humans, not computers
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse support
set -g mouse on

# ==========================
# ===   Key bindings     ===
# ==========================

# Unbind default key bindings, we're going to override
unbind "\$" # rename-session
unbind ,    # rename-window
unbind %    # split-window -h
unbind '"'  # split-window
#unbind }    # swap-pane -D
#unbind {    # swap-pane -U
unbind [    # paste-buffer
unbind ]    
unbind "'"  # select-window
# unbind n    # next-window
# unbind p    # previous-window
unbind l    # last-window
unbind M-n  # next window with alert
unbind M-p  # next window with alert
unbind o    # focus thru panes
unbind &    # kill-window
unbind "#"  # list-buffer 
unbind =    # choose-buffer
unbind z    # zoom-pane
unbind M-Up  # resize 5 rows up
unbind M-Down # resize 5 rows down
unbind M-Right # resize 5 rows right
unbind M-Left # resize 5 rows left

# Edit configuration and reload
bind C-e new-window -n 'tmux.conf' "sh -c '\${EDITOR:-vim} ~/.tmux.conf && tmux source ~/.tmux.conf && tmux display \"Config reloaded\"'"

# Reload tmux configuration 
bind C-r source-file ~/.tmux.conf \; display "Config reloaded"

# new window and retain cwd
bind c new-window -c "#{pane_current_path}"

# Prompt to rename window right after it's created
set-hook -g after-new-window 'command-prompt -I "#{window_name}" "rename-window '%%'"'

# Rename session and window
bind r command-prompt -I "#{window_name}" "rename-window '%%'"
bind R command-prompt -I "#{session_name}" "rename-session '%%'"

# Split panes
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# Select pane and windows
bind -r C-[ previous-window
bind -r C-] next-window
bind -r [ select-pane -t :.-
bind -r ] select-pane -t :.+
bind -r Tab last-window   # cycle thru MRU tabs
bind -r C-o swap-pane -D

# Zoom pane
bind + resize-pane -Z

# Link window
bind L command-prompt -p "Link window from (session:window): " "link-window -s %% -a"

# Swap panes back and forth with 1st pane
# When in main-(horizontal|vertical) layouts, the biggest/widest panel is always @1
# bind \ if '[ #{pane_index} -eq 1 ]' \
#     'swap-pane -s "!"' \
#     'select-pane -t:.1 ; swap-pane -d -t 1 -s "!"'

# Kill pane/window/session shortcuts
bind x kill-pane
bind X kill-window
bind C-x confirm-before -p "kill other windows? (y/n)" "kill-window -a"
bind Q confirm-before -p "kill-session #S? (y/n)" kill-session

# Merge session with another one (e.g. move all windows)
# If you use adhoc 1-window sessions, and you want to preserve session upon exit
# but don't want to create a lot of small unnamed 1-window sessions around
# move all windows from current session to main named one (dev, work, etc)
bind C-u command-prompt -p "Session to merge with: " \
   "run-shell 'yes | head -n #{session_windows} | xargs -I {} -n 1 tmux movew -t %%'"

# Detach from session
bind d detach
bind D if -F '#{session_many_attached}' \
    'confirm-before -p "Detach other clients? (y/n)" "detach -a"' \
    'display "Session has only 1 client attached"'

# Hide status bar on demand
bind C-s if -F '#{s/off//:status}' 'set status off' 'set status on'

# U/D/L/R HJKL selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
```

**Comment by cflynn07** [comment]
Figured it out, syntax error in my `/Users/casey/.config/powerline/colorschemes/default.json` file
