### ISSUE TITLE
tmux 2.9 status_left not showing correctly

### ISSUE THREAD

**Issue by haoyouab** [powerline/powerline#2080]
My tmux version was 2.8 and it's upgraded along with the distribution (Fedora in my case) to 2.9. The status bar of the left are not showing correctly as before anymore. See it as before:

![image](https://user-images.githubusercontent.com/19225626/76177347-e167ac00-61ee-11ea-9ba3-c2ee55345544.png)

After:
![image](https://user-images.githubusercontent.com/19225626/76177372-f8a69980-61ee-11ea-9238-5dcbe48be725.png)

BTW,
$ powerline-config tmux setup
gives me this:
Traceback (most recent call last):
  File "/usr/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/usr/lib/python3.7/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/powerline/bindings/config.py", line 215, in tmux_setup
    source_tmux_files(pl, args, tmux_version=tmux_version, source_tmux_file=stf)
  File "/usr/lib/python3.7/site-packages/powerline/bindings/config.py", line 74, in source_tmux_files
    source_tmux_file(os.path.join(TMUX_CONFIG_DIRECTORY, 'powerline-base.conf'))
  File "/usr/lib/python3.7/site-packages/powerline/bindings/config.py", line 196, in source_tmux_file_nosource
    with open(fname) as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/tmux/powerline-base.conf'

Any idea why? The status bar on the right works fine though.

**Comment by PH111P** [comment]
Could this perhaps be related to https://github.com/powerline/powerline/issues/2005?

**Comment by haoyouab** [comment]
@PH111P Oh yes it seems so! I believe it's been fixed and I updated my config file a bit and it works as usual.
