### ISSUE TITLE
vim tabline raises when using popup window

### ISSUE THREAD

**Issue by leophys** [powerline/powerline#2125]
Hi, thanks for this awesome software!

### The issue

I recently updated my vim plugins, and this included an update to [`fzf.vim`](https://github.com/junegunn/fzf/commit/c60ed1758315f0d993fbcbf04459944c87e19a48) that enabled by default the popup window as preview mode. If I have multiple tabs opened, and then call, let say, `fzf.vim`'s `:Buffer`, I get this stacktrace and the tabline falls back to the vim default one:

```
Traceback (most recent call last):                                                                                                                                                                                 
  File "<string>", line 1, in <module>                                                                                                                                                                             
  File "/usr/lib/python3.8/site-packages/powerline/vim.py", line 305, in tabline                                                                                                                                   
    return self.render(*self.win_idx(None), is_tabline=True)                                                                                                                                                       
TypeError: render() argument after * must be an iterable, not NoneType                                                                                                                                             
E858: Eval did not return a valid python object
```

### Temporary workaround

This config disables the nice popup window for `fzf.vim`:

```
let g:fzf_layout = { 'down': '40%' }
```

### I'd like to help...

...but  I am not able to step-debug `vim.py` while executing vim. Do you have any suggestions, a part from using a lot of `print`s inside the python code?

Thanks

**Comment by luc1ph3r** [comment]
I opened a [PR](https://github.com/powerline/powerline/pull/2132) for that.

I looked at `statusline()`, and it seems that it tries to render a current window if `self.win_idx(None)`  returned `None`. So I did the same in `tabline()` for consistency.

**Comment by leophys** [comment]
The PR works.
