### ISSUE TITLE
Command not available error for vim plugin

### ISSUE THREAD

**Issue by choonming** [powerline/powerline#2137]
I have installed powerline-status using pip and followed the instructions here https://powerline.readthedocs.io/en/master/usage/other.html#vim-statusline to install the vim plugin. However, I got the following error:

```
Error detected while processing /Users/choonming/.vimrc:
line    1:
E319: Sorry, the command is not available in this version: python3 from powerline.vim import setup as powerline_setup
line    2:
E319: Sorry, the command is not available in this version: python3 powerline_setup()
line    3:
E319: Sorry, the command is not available in this version: python3 del powerline_setup
Press ENTER or type command to continue
```

here is my `.vimrc` configuration:
```
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup
```

```
$ python --version
Python 3.8.2
```

```
$ pip show powerline-status
Name: powerline-status
Version: 2.7
Summary: The ultimate statusline/prompt utility.
Home-page: https://github.com/powerline/powerline
Author: Kim Silkebaekken
Author-email: kim.silkebaekken+vim@gmail.com
License: MIT
Location: /Library/Python/3.8/site-packages
Requires:
Required-by:
```

OS: Mac OS Catalina 10.15.7

**Comment by PH111P** [comment]
It looks like your vim doesn't have python support. You can check this via `vim --version | grep python`.

**Comment by choonming** [comment]
@PH111P this is my output
```
vim --version | grep python
+cmdline_hist      -langmap           +python/dyn        +visual
+cmdline_info      +libcall           -python3           +visualextra
```

**Comment by choonming** [comment]
I see it now. Thanks. I will try to resolve this by installing vim from brew

**Comment by choonming** [comment]
Now I'm getting a different error with vim after installing vim with python support:
```
im --version | grep python
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -lpython3.9 -framework CoreFoundation  -lruby.2.7
```

```Error detected while processing /Users/choonming/.vimrc:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'powerline'
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined
```

**Comment by PH111P** [comment]
Perhaps your `pip` installed `powerline` for python2 (which is unsupported)?
You can check whether powerline is correctly installed by running the following in your python3 interpreter of choice:
``` python
from powerline.vim import setup as powerline_setup
```
