### ISSUE TITLE
Installation issue with tmux

### ISSUE THREAD

**Issue by leodahal4** [powerline/powerline#2141]
I am not being able to figure out a problem.
I am on, kali with fish shell.
At first i noticed that my powerline theme was not started for tmux and then I tried to source like,
powerline-config tmux setup
But that too returns a error.

I did also tried to install as,
$ pip3 install powerline --no-cache-dir
Collecting powerline
  Downloading powerline-0.2.4.tar.bz2 (61 kB)
     |████████████████████████████████| 61 kB 350 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-10h55057/powerline/setup.py'"'"'; __file__='"'"'/tmp/pip-install-10h55057/powerline/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6k3cw4b7
         cwd: /tmp/pip-install-10h55057/powerline/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-10h55057/powerline/setup.py", line 6
        setup(
         ^
    SyntaxError: keyword argument repeated: zip_safe
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Can anyone help me out?

**Comment by laebshade** [comment]
The `powerline` package is not the one you're looking for: https://pypi.org/project/powerline/

`powerline-status` is: https://pypi.org/project/powerline-status/

Please see the instructions: https://powerline.readthedocs.io/en/latest/installation.html#pip-installation
