### ISSUE TITLE
Errors on OSX when clicking ctrl+c

### ISSUE THREAD

**Issue by REPTILEHAUS** [powerline/powerline#2153]
```
^CTraceback (most recent call last):
  File "/usr/local/bin/powerline-render", line 31, in <module>
    write_output(args, powerline, segment_info, get_unicode_writer())
  File "/Library/Python/3.8/site-packages/powerline/commands/main.py", line 184, in write_output
    rendered = powerline.render(
  File "/Library/Python/3.8/site-packages/powerline/__init__.py", line 876, in render
    self.update_renderer()
  File "/Library/Python/3.8/site-packages/powerline/__init__.py", line 859, in update_renderer
    self.create_renderer(**cr_kwargs)
  File "/Library/Python/3.8/site-packages/powerline/__init__.py", line 689, in create_renderer
    renderer = Renderer(**self.renderer_options)
  File "/Library/Python/3.8/site-packages/powerline/renderers/shell/__init__.py", line 20, in __init__
    super(PromptRenderer, self).__init__(**kwargs)
  File "/Library/Python/3.8/site-packages/powerline/renderer.py", line 170, in __init__
    self.theme = Theme(theme_config=theme_config, **theme_kwargs)
  File "/Library/Python/3.8/site-packages/powerline/theme.py", line 96, in __init__
    segment = get_segment(segment, side)
  File "/Library/Python/3.8/site-packages/powerline/segment.py", line 328, in get
    contents, _contents_func, module, function_name, name = get_segment_info(data, segment)
  File "/Library/Python/3.8/site-packages/powerline/segment.py", line 67, in get_function
    function = data['get_module_attr'](module, function_name, prefix='segment_generator')
  File "/Library/Python/3.8/site-packages/powerline/__init__.py", line 392, in get_module_attr
    return getattr(__import__(module, fromlist=(attr,)), attr)
  File "/Library/Python/3.8/site-packages/powerline/segments/common/net.py", line 8, in <module>
    from powerline.lib.url import urllib_read
  File "/Library/Python/3.8/site-packages/powerline/lib/url.py", line 6, in <module>
    from urllib.request import urlopen  # NOQA
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 88, in <module>
    import http.client
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 71, in <module>
    import email.parser
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/email/feedparser.py", line 31, in <module>
    NLCRE = re.compile(r'\r\n|\r|\n')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/re.py", line 250, in compile
    return _compile(pattern, flags)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/re.py", line 302, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/sre_compile.py", line 768, in compile
    code = _code(p, flags)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/sre_compile.py", line 604, in _code
    _compile_info(code, p, flags)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/sre_compile.py", line 590, in _compile_info
    charset, hascased = _optimize_charset(charset)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/sre_compile.py", line 285, in _optimize_charset
    if op is LITERAL:
KeyboardInterrupt
```

**Comment by PH111P** [comment]
Could you please provide some additional context (shell/powerline-binding, versions of involved programs, etc)? Thanks,

**Comment by REPTILEHAUS** [comment]
Sure its powerline shell Im running python 3.8 OSX big sur

**Comment by PH111P** [comment]
Are you per chance using the IMAP segment in your shell? It somehow looks like you pressed `CTRL+C` exactly while that segment was updating.

**Comment by REPTILEHAUS** [comment]
Not that I am aware of anyway, this happens every time i press ctrl+c twice in fast succession, if i do it slowly it doesnt cause the error output

**Comment by PH111P** [comment]
Can you share your powerline config?

**Comment by REPTILEHAUS** [comment]
Im using the default config but removed the smtp stuff from wm/default.conf

```
{
	"segments": {
		"right": [
			{
				"function": "powerline.segments.common.time.date"
			},
			{
				"function": "powerline.segments.common.time.date",
				"name": "time",
				"args": {
					"format": "%H:%M",
					"istime": true
				}
			}
		]
	}
}
```


and also if needed my shell config is:

```
{
	"segments": {
		"left": [
			{
				"function": "powerline.segments.shell.mode"
			},
			{
				"function": "powerline.segments.common.net.hostname",
				"priority": 10
			},
			{
				"function": "powerline.segments.common.env.user",
				"priority": 30
			},
			{
				"function": "powerline.segments.common.env.virtualenv",
				"priority": 50
			},
			{
				"function": "powerline.segments.shell.cwd",
				"priority": 10
			},
			{
				"function": "powerline.segments.shell.jobnum",
				"priority": 20
			}
		],
		"right": [
			{
				"function": "powerline.segments.shell.last_pipe_status",
				"priority": 10
			},
			{
				"function": "powerline.segments.common.vcs.stash",
				"priority": 50
			},
			{
				"function": "powerline.segments.common.vcs.branch",
				"priority": 40
			}
		]
	}
}

```
