### ISSUE TITLE
ImportError: No module named typing

### ISSUE THREAD

**Issue by moonwatcher-monster** [powerline/powerline#2166]
I am preparing to install powerline while modifing my iterm2. When I input this command: pip install --user powerline-status, it happens with ImportError. My OS is Mac OS Catalina.

Last login: Fri Apr 30 11:35:58 on ttys000
➜  ~ pip install --user powerline-status
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==21.1', 'console_scripts', 'pip')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/pip-21.1-py2.7.egg/pip/__init__.py", line 1, in <module>
    from typing import List, Optional
ImportError: No module named typing
![截屏2021-04-30 22 04 14](https://user-images.githubusercontent.com/83410263/116706369-260c6300-aa00-11eb-9684-4c6fc5ba967e.png)

**Comment by PH111P** [comment]
I'm sorry, but python2 is not supported anymore.
