### ISSUE TITLE
`vim-powerline` crashes under `pipenv`

### ISSUE THREAD

**Issue by abitrolly** [powerline/powerline#2168]
```
$ pipenv shell

(venv) $ vim
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'powerline'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'powerline'
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Unable to import powerline, is it installed?
Press ENTER or type command to continue
```

**Comment by abitrolly** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1961110
