### ISSUE TITLE
Powerline-daemon giving error libffi.so.7: cannot open shared object file

### ISSUE THREAD

**Issue by farzadmf** [powerline/powerline#2182]
Hi,

Today when I updated my packages in Manjaro Linux, I'm getting this error when I run `powerline-daemon`:
```
Traceback (most recent call last):
  File "/home/farzad/.asdf/installs/python/3.9.7/bin/powerline-daemon", line 23, in <module>
    from powerline.shell import ShellPowerline
  File "/home/farzad/.asdf/installs/python/3.9.7/lib/python3.9/site-packages/powerline/__init__.py", line 11, in <module>
    from powerline.lib.config import ConfigLoader
  File "/home/farzad/.asdf/installs/python/3.9.7/lib/python3.9/site-packages/powerline/lib/config.py", line 12, in <module>
    from powerline.lib.watcher import create_file_watcher
  File "/home/farzad/.asdf/installs/python/3.9.7/lib/python3.9/site-packages/powerline/lib/watcher/__init__.py", line 7, in <module>
    from powerline.lib.watcher.inotify import INotifyFileWatcher
  File "/home/farzad/.asdf/installs/python/3.9.7/lib/python3.9/site-packages/powerline/lib/watcher/inotify.py", line 6, in <module>
    import ctypes
  File "/home/farzad/.asdf/installs/python/3.9.7/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

I have the latest version of `powerline` installed (`2.8.2`).

Please let me know if there's any other information I can provide to troubleshoot this.

**Comment by PH111P** [comment]
It seems that you are missing `libffi.so.7`, perhaps it got removed with your update?
