### ISSUE TITLE
Unable to import powerline, is it installed? Windows 10 

### ISSUE THREAD

**Issue by boomshankerx** [powerline/powerline#2227]
I'm having an issue with vim-powerline on windows around the time that the latest builds moved to Python 3.11. I've tried reinstalling everything from scratch. All other python plugins are working. Am I missing something or is this a bug. 

Windows 10 22H2

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan  6 2023 23:29:39)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1153

Python 3.11.1 x64

## Error
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'powerline'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "C:\Users\user\vimfiles\bundle\powerline\powerline\__init__.py", line 
10, in <module>
    from powerline.colorscheme import Colorscheme
  File "C:\Users\user\vimfiles\bundle\powerline\powerline\colorscheme.py
", line 6, in <module>
    from powerline.lib.unicode import unicode
  File "C:\Users\user\vimfiles\bundle\powerline\powerline\lib\unicode.py",
line 7, in <module>
    from unicodedata import east_asian_width, combining
ModuleNotFoundError: No module named 'unicodedata'
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Unable to import powerline, is it installed?
```

## sys.path
```
['', 'C:\\Program Files\\Python311\\python311.zip', 'C:\\Program Files\\Python311\\Lib', 'C:\\Program Files\\Python311\\DLLs', 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages', 'C:\\Program Files\\Python311', 'C:\\Program Files\\Python311\\Lib\\site-packages']
```
## Python CLI
What is interesting is that I can import the offending module manually with no error. Very strange.

```
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import unicodedata
>>> from unicodedata import east_asian_width, combining
>>>
```

**Comment by pcxmac** [comment]
in linux, I have to link to it in my PYTHONPATH, ln -s ~/.powerline/powerline > ~./.local/.../site-packages/...

not sure about it not finding unicodedata. I run 3.10.10

**Comment by boomshankerx** [comment]
The problem seems to have been introduced with Python 3.11 on Windows. I haven't been able to get it to work.
