### ISSUE TITLE
metadata-generation-failed when installing on on python 3.11/macOS 12

### ISSUE THREAD

**Issue by iluvcapra** [powerline/powerline#2231]
I've tried legacy-resolver and the other usual tricks, not really sure what's going on.

```
$ pip3.11 install powerline                                                                                              
Collecting powerline
  Using cached powerline-0.2.4.zip (79 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ys/qptb5nl92lv88nxcf5wqrmy00000gn/T/pip-install-l_p8fczv/powerline_dafb50133deb4120b7bdb5c6c269f2e3/setup.py", line 27
          zip_safe = False,
          ^^^^^^^^^^^^^^^^
      SyntaxError: keyword argument repeated: zip_safe
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by iluvcapra** [comment]
Sorry installed wrong thing.
