### ISSUE TITLE
setup fails for development version of tmux 

### ISSUE THREAD

**Issue by mgkurtz** [powerline/powerline#2232]
A `tmux` built from the git repository, results in the tmux-bindings not working due to `powerline-config tmux setup` exiting with exit code 1.

The current implementation assumes the tmux version string to be like `tmux master`, `tmux 3.3` or `tmux 3.3a`. This is right for releases, but otherwise it could also be `tmux 3.3-rc` or `tmux next-3.4`.

<details>

<summary>Error traceback</summary>

Output of `powerline-config tmux setup`

```
Traceback (most recent call last):
  File ".../bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File ".../site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File ".../site-packages/powerline/bindings/config.py", line 184, in tmux_setup
    tmux_version = get_tmux_version(pl)
  File ".../site-packages/powerline/bindings/tmux/__init__.py", line 84, in get_tmux_version
    return TmuxVersionInfo(int(major), int(minor), suffix)
ValueError: invalid literal for int() with base 10: 'next-3'
```
</details>

<details>
<summary>Tmux version numbers according to git log</summary>

Output of `git log --all -G'AC_INIT' --patch | grep '+AC_INIT'` in the tmux repository:

```
+AC_INIT([tmux], 3.3a)
+AC_INIT([tmux], next-3.4)
+AC_INIT([tmux], 3.3)
+AC_INIT([tmux], next-3.4)
+AC_INIT([tmux], next-3.4)
+AC_INIT([tmux], 3.3-rc)
+AC_INIT([tmux], next-3.4)
+AC_INIT([tmux], 3.3-rc)
+AC_INIT([tmux], 3.2a)
+AC_INIT([tmux], 3.2)
+AC_INIT([tmux], 3.2-rc5)
+AC_INIT([tmux], next-3.3)
+AC_INIT([tmux], next-3.3)
+AC_INIT([tmux], 3.2-rc3)
+AC_INIT([tmux], next-3.3)
+AC_INIT([tmux], 3.2-rc2)
+AC_INIT([tmux], next-3.3)
+AC_INIT([tmux], 3.2-rc)
+AC_INIT([tmux], next-3.3)
+AC_INIT([tmux], 3.2-rc)
+AC_INIT([tmux], 3.1b)
+AC_INIT([tmux], 3.1a)
+AC_INIT([tmux], 3.1)
+AC_INIT([tmux], 3.1-rc4)
+AC_INIT([tmux], 3.1-rc3)
+AC_INIT([tmux], next-3.2)
+AC_INIT([tmux], 3.1-rc2)
+AC_INIT([tmux], next-3.2)
+AC_INIT([tmux], 3.1-rc)
+AC_INIT([tmux], 3.0a)
+AC_INIT([tmux], 3.0)
+AC_INIT([tmux], 3.0-rc5)
+AC_INIT([tmux], next-3.1)
+AC_INIT([tmux], 3.0-rc4)
+AC_INIT([tmux], 3.0-rc3)
+AC_INIT([tmux], 3.0-rc2)
+AC_INIT([tmux], next-3.1)
+AC_INIT([tmux], 3.0-rc)
+AC_INIT([tmux], 2.9a)
+AC_INIT([tmux], 2.9)
+AC_INIT([tmux], 2.9-rc3)
+AC_INIT([tmux], 2.9-rc2)
+AC_INIT([tmux], next-3.0)
+AC_INIT([tmux], 2.9-rc)
+AC_INIT([tmux], next-2.9)
+AC_INIT(tmux, 2.8)
+AC_INIT(tmux, master)
+AC_INIT(tmux, 2.8-rc)
+AC_INIT(tmux, 2.7)
+AC_INIT(tmux, master)
+AC_INIT(tmux, 2.7-rc)
+AC_INIT(tmux, 2.6)
+AC_INIT(tmux, master)
+AC_INIT(tmux, 2.6-rc3)
+AC_INIT(tmux, 2.6-rc2)
+AC_INIT(tmux, master)
+AC_INIT(tmux, 2.6-rc)
+AC_INIT(tmux, master)
+AC_INIT(tmux, 2.6-rc)
+AC_INIT(tmux, 2.5)
+AC_INIT(tmux, 2.5-rc2)
+AC_INIT(tmux, master)
+AC_INIT(tmux, 2.5-rc)
+AC_INIT(tmux, 2.4)
+AC_INIT(tmux, master)
+AC_INIT(tmux, 2.4)
+AC_INIT(tmux, 2.3)
+AC_INIT(tmux, 2.2)
+AC_INIT(tmux, 2.1)
+AC_INIT(tmux, 2.0)
+AC_INIT(tmux, 1.10)
+AC_INIT(tmux, 1.9a)
+AC_INIT(tmux, 1.10)
+AC_INIT(tmux, 1.9)
+AC_INIT(tmux, 1.8)
+AC_INIT(tmux, 1.7)
+AC_INIT(tmux, 1.6)
+AC_INIT(tmux, 1.5)
```
</details>

So, maybe in https://github.com/powerline/powerline/blob/833f30e88efa51246dadc6daf21638ec61b6b912/powerline/bindings/tmux/__init__.py#L75 we could just search the version string for the proper version number? Something like

```python
major, minor, suffix = re.search('([0-9]+)\.([0-9])+([a-z]*)', version_string).groups()
```
perhaps?

Alternatively, we could merge #1991 or #2201.

**Comment by PH111P** [comment]
Please make sure to have the latest powerline installed. See https://github.com/powerline/powerline/issues/1992
