### ISSUE TITLE
setup.py syntax error

### ISSUE THREAD

**Issue by guyzmo** [powerline/powerline#34]
Hello,

I think in last version posted to pipy, there's a glitch in the setup file. It looks like you put two times the zip_safe in the setup.py file.

```
Downloading/unpacking powerline
  Downloading powerline-0.2.4.zip (79kB): 79kB downloaded
  Running setup.py egg_info for package powerline
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/var/folders/pm/pmEvZQRMFJ8H9Sfw2IZGgU+++TM/-Tmp-/pip-build/powerline/setup.py", line 27
        zip_safe = False,
    SyntaxError: keyword argument repeated
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/var/folders/pm/pmEvZQRMFJ8H9Sfw2IZGgU+++TM/-Tmp-/pip-build/powerline/setup.py", line 27

    zip_safe = False,

SyntaxError: keyword argument repeated

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /var/folders/pm/pmEvZQRMFJ8H9Sfw2IZGgU+++TM/-Tmp-/pip-build/powerline
```

here's a little patch, if that helps:

```
diff --git a/setup.py b/setup.py.patched
index 41b8b12..048d2f9 100644
--- a/setup.py
+++ b/setup.py.a
@@ -24,7 +24,6 @@ setup(
                        'templates/data/images/*'
                ]
        },
-   zip_safe = False,

        install_requires = [
                'setuptools>=0.6b1',
```

HTH

**Comment by Maltimore** [comment]
Indeed. This is still a problem in 2018!

**Comment by hjoliver** [comment]
No it's not. `pip install powerline-status`

https://powerline.readthedocs.io/en/latest/installation.html#pip-installation

**Comment by Maltimore** [comment]
Fair enough.
