### ISSUE TITLE
Qtile plugin crashes on a clean install

### ISSUE THREAD

**Issue by RedKrieg** [powerline/powerline#351]
When trying to load the Qtile plugin via the instructions [here](https://powerline.readthedocs.org/en/latest/overview.html#qtile-widget) applied to the [default config](https://github.com/qtile/qtile/blob/master/libqtile/resources/default_config.py) for qtile, qtile crashes with the following traceback:
```
Traceback (most recent call last):
  File "/usr/bin/qtile", line 77, in <module>
    q = make_qtile()
  File "/usr/bin/qtile", line 72, in make_qtile
    no_spawn=options.no_spawn)
  File "/usr/lib/python2.7/dist-packages/libqtile/manager.py", line 756, in __init__
    self._process_screens()
  File "/usr/lib/python2.7/dist-packages/libqtile/manager.py", line 830, in _process_screens
    self.groups[i],
  File "/usr/lib/python2.7/dist-packages/libqtile/manager.py", line 193, in _configure
    i._configure(qtile, self)
  File "/usr/lib/python2.7/dist-packages/libqtile/bar.py", line 177, in _configure
    i._configure(qtile, self)
  File "/home/redkrieg/.local/lib/python2.7/site-packages/powerline/bindings/qtile/widget.py", line 29, in _configure
    base._TextBox._configure(self, qtile, bar)
  File "/usr/lib/python2.7/dist-packages/libqtile/widget/base.py", line 221, in _configure
    self.foreground,
AttributeError: 'Powerline' object has no attribute 'foreground'
```
The [_TextBox docstring](https://github.com/qtile/qtile/blob/master/libqtile/widget/base.py#L160) states that foreground (among other attributes) must have defaults added, so I added some self.* definitions for the properties mentioned, but still do not see the powerline output.  I no longer receive a traceback after adding these to the __init__ function:
```
self.foreground = "FFFFFF"
self.background = "000000"
self.padding = 0 # I may have set a float here, don't recall
self._font = "inconsolata"
self._fontsize = 11.0 # definitely set a float here
```
I still do not see the powerline widget.

Have I missed a part of the configuration?

**Comment by ZyX-I** [comment]
Closing because this issue is too old, qtile bindings were updated and it seems it does not touch other users.
